### ISSUE TITLE
how to apply final_scale_limits option from infercnv ?

### ISSUE THREAD

**Issue by hzongyao** [theMILOlab/SPATA2#10]
Hi 
The infercnv package provides "final_scale_limits" option,which  can help keep the scale of plot same for visualization, I wonder that how to apply final_scale_limits option from infercnv in SPATA2 ? Thank you !

**Comment by kueckelj** [comment]
Hi hzongyao, the 'final_scale_limits' option is currently not implemented in SPATA2. I will let you know once I've done this. 

Best regards

Jan
