### ISSUE TITLE
Error runBayesSpaceClustering

### ISSUE THREAD

**Issue by juliach2** [theMILOlab/SPATA2#100]
Hallo,

After denoising and plotting via plotSurface I run into an error when trying to cluster the data:

spata_obj <- 
  runBayesSpaceClustering(
    object = spata_obj, 
    name = "bayes_space" 
  )

First I get the Error:
Error in file(file, "rt") : cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file 'xx/outs/spatial/tissue_positions_list.csv': No such file or directory

As Space Ranger changed the name of tissue_positions_list.csv I changed the filename tissue_positions.csv to tissue_positions_list.csv manually.

After re-running I now get this error:
Error in .subscript.2ary(x, , j, drop = TRUE) : subscript out of bounds

I tried it with my datasets, as well as the tutorial dataset.

I have the impression that it might be a problem with the changes in datastructure of seurat 5 as I get:
> getGroupingOptions(spata_obj)
               factor                factor                factor                factor 
         "orig.ident" "Spatial_snn_res.0.8"     "seurat_clusters"           "histology" 

I am using SPATA2 2.0.4 and Seurat 5.0.1.
I tried to downgrade to seurat 4 but run ito the error reported in issue #99. Re-installing confuns did not fix it.

Is there a workaround?

Thank you!

**Comment by kueckelj** [comment]
Hello, actually I think it is a problem with the BayesSpace package itself. Can you try and create a SingleCell object with BayesSpace::readVisium() using the directory you used to create the spata2 object? Do you run into the same errors if you do so?

**Comment by kueckelj** [comment]
Can you reinstall SPATA2 and try again?
