### ISSUE TITLE
plotSurface(object_t269, color_by = "Seurat", pt_clrp = "jama")

### ISSUE THREAD

**Issue by healthgreat** [theMILOlab/SPATA2#107]
plotSurface(object_t269, color_by = "Seurat", pt_clrp = "jama")
22:03:20 Joining 1 feature.
22:03:22 Done.
Error in grid.Call.graphics(C_points, x$x, x$y, x$pch, x$size) : 
  **cannot allocate memory block of size 134217728 Tb**
In addition: Warning message:
In color_vector(clrp = clrp, names = names, clrp.adjust = clrp.adjust) :
  Chosen colorpalette 'jama' provides 10 colors. Need 14 colors. Returning 'default' colorpalette.

**Comment by simonmfr** [comment]
Hi, this is a memory error, please either increase RAM or use a subset of the object.
