### ISSUE TITLE
Adding manual trajectory object based on the metadata

### ISSUE THREAD

**Issue by Qirongmao97** [theMILOlab/SPATA2#110]
Dear SPATA2 developers,

Thanks for developing SPATA2, a very comprehensive tool for analyzing spatial transcriptomics!

One question for the spatial trajectory screening, can I add the trajectory object using manual metadata instead of assigning coordinates and direction (addSpatialTrajectory)? Since I'm interested in spots near the hotspot area, and we have multiple hotspots in our sample.

**Comment by simonmfr** [comment]
Hi @Qirongmao97, thank you for getting in touch. Currently it is not possible to directly input metadata into ``addSpatialTrajectory()``, but you can directly input x and y coordinates of barcode spots. 

Therefore, I recommend to extract the barcode spots of interest based on your custom metadata using ``getFeatureDf(spata_object)``, then filtering the coordinates of these barcode spots using ``getCoordsDf(spata_object)``, and lastly using the coordinates x and y for your Spatial Trajectory, for instance: ``addSpatialTrajectory(spata_object, id="test", start=c(100,100), end=c(200,200), width=3)``. Does that help?

**Comment by simonmfr** [comment]
Closed due to inactivity - feel free to open if necessary
