### ISSUE TITLE
Error in purrr::map(.x = seq_along(id), .f = function(i) { : Caused by error in `map_df()`: ! could not find function "map_df"

### ISSUE THREAD

**Issue by cubense** [theMILOlab/SPATA2#112]
Dear SPATA2 team,
I wanna do the "Image Annotation Screening" in my project. 
when I do the 5.1 Visualization step,  

```
#using ten circle bins to visualize the concept
 ias_layer_bins <- ggpLayerEncirclingIAS(object = object,distance = "1mm", n_bins_circle = 6, id = "tip_center",line_size = 1 ) 

```
and I got this error

Specified `distance` = 1mm and `n_bins_circle` = 7. Calculated `binwidth` = 0.1429mm.
Error in `purrr::map()`:
i In index: 1.
Caused by error in `map_df()`:
! could not find function "map_df"
Backtrace:
 1. SPATA2::ggpLayerEncirclingIAS(...)
 2. purrr::map(...)
 3. purrr:::map_("list", .x, .f, ..., .progress = .progress)
 7. SPATA2 (local) .f(.x[[i]], ...)
 
I have try to reinstall purrr, but I got the same error. what should I do.

**Comment by simonmfr** [comment]
HI @cubense, sorry for the delay. We have now released a major update to SPATA2 v3, please re-install and re-try following the new [Spatial Annotation Screening tutorial](https://themilolab.github.io/SPATA2/articles/spatial-annotation-screening.html). If any issue persists, feel free to re-open.
