### ISSUE TITLE
tissueOutlineIdentified(object) is not TRUE

### ISSUE THREAD

**Issue by MatteoRiva95** [theMILOlab/SPATA2#114]
Good morning everyone,

I am trying to use this command, in order to actually see the outlines of the tissue in my spatial:

tissue_outline <- ggpLayerTissueOutline(object = object)

But it returns this error:

Error in getTissueOutlineDf(object) : 
  tissueOutlineIdentified(object) is not TRUE
Called from: base::stopifnot(tissueOutlineIdentified(object))

I don't understand why. object is a spata2 object.
Is it possible to solve this issue please?

Thank you so much!

**Comment by kueckelj** [comment]
Hi. Have you used object <- identifyTissueOutline(object) beforehand?

**Comment by MatteoRiva95** [comment]
@kueckelj thank you so much for your reply!
I did not use it because it is not present in the following tutorial:

https://themilolab.github.io/SPATA2/articles/spata-v2-spatial-trajectories.html

Still, I used your command suggestion (identifyTissueOutline), but it gives me back this error:

Error in SPATA2::identifyTissueOutline(.) : 
  tissueSectionsIdentfied(object) is not TRUE
  
Thank you again for your help

**Comment by kueckelj** [comment]
Hey, sorry for the late reply. You need to run `object <- identifyTissueSections(object)` , first. Does it work then?

**Comment by MatteoRiva95** [comment]
@kueckelj thank you for your reply.
object <- identifyTissueSections(object) works, but unfortunately when I run tissue_outline <- SPATA2::ggpLayerTissueOutline(object = object), it returns this error again:

17:38:14 Using center to center distance to compute pixel scale factor.
17:38:14 Computing barcode spot distances.
17:38:36 Done.
Error in getTissueOutlineDf(object) : 
  tissueOutlineIdentified(object) is not TRUE
  
The lines I am running right now are just these two:

spata.1 <- SPATA2::identifyTissueSections(spata.1)
tissue_outline <- SPATA2::ggpLayerTissueOutline(object = spata.1)

**Comment by MatteoRiva95** [comment]
@kueckelj Sorry, I finally did it. I misunderstood what you meant and running these three lines:

object <- SPATA2::identifyTissueOutline(object)
object <- SPATA2::identifyTissueSections(object)
tissue_outline <- SPATA2::ggpLayerTissueOutline(object = object)

it finally works :) I only suggest to update the tutorial adding these two lines (identifyTissueOutline and identifyTissueSections) for other users too!

Thank you @kueckelj for your kind help
