### ISSUE TITLE
how use cluster message to do Spatial Trajectory Analysis

### ISSUE THREAD

**Issue by Liripo** [theMILOlab/SPATA2#12]
I would like to ask if I can do `Spatial Trajectory Analysis` without using the shiny interactive mode. Instead use cluster to do `Spatial Trajectory Analysis`

**Comment by kueckelj** [comment]
Hello Liripo, I don't understand what exactly you are trying to do. Do you want to use a high performance cluster to run the analysis from terminal?

In general: 

The interactive shiny application opened with `createTrajectories()`  is only used to set up a spatial trajectory - to define its start and end points. Apart from that every subsequent function like `assessTrajectoryTrends()` must be called manually.

Defining spatial trajectories: interactive mode 
Analysing spatial trajectories: manual 

Does that help?

**Comment by Liripo** [comment]
I‘m sorry. I did not say it clearly. Example,like stlearn do:
![image](https://user-images.githubusercontent.com/54770415/135185675-b6233783-066b-41d2-9376-aaf43c0a1cc8.png)

**Comment by kueckelj** [comment]
Okay, so do you want to draw a trajectory from one cluster to another cluster? In this case you'd have to use the interactive application, too. You can change the coloring of the spatial plot within the application of `createTrajectories()` to the cluster variable of you choice and then draw trajectories from one cluster to another or even connect several clusters with each other.

**Comment by Liripo** [comment]
Thank you.Will it support programming mode in the future,rather than manually picking it?

**Comment by kueckelj** [comment]
For that I need to know exactly what you need. Do I get this right, that you want to define a trajectory with a function call like: 

`object <- createTrajectoryManually(object = object, start = c(x = 50, y = 50), end = c(x = 100, y = 100), trajectory_name = "example") `

Here arguments `start` and `end` take numeric vectors of length 2 respectively definining start and endpoint of the trajectory.

**Comment by Liripo** [comment]
yes,this is! thank you for your help！！

**Comment by kueckelj** [comment]
I have added the function `createTrajectoryManually()`. You should be able to use it if you reinstall SPATA2. Does it solve your problem?
