### ISSUE TITLE
Difference between SPATA2 plotSurface and SPATA2 plotSurfaceInteractive

### ISSUE THREAD

**Issue by Rohitarora21** [theMILOlab/SPATA2#13]
plotSurface(object = obj,
              color_by = "MYC",
              pt_alpha	= 0.85,
              pt_size = 2.75,
              pt_clrsp = "YlOrRd")

While in interactive the plot appears differently.

I was wondering why this difference existed and how to make my plotSurface look like my plotSurfaceInteractive, to clarify, I have not run denoising yet. I was also wondering if there was a way to display positive spots on top of zero spots.

**Comment by Rohitarora21** [comment]
to clarify, I have not run denoising on the data yet

**Comment by kueckelj** [comment]
Hello Rohitarora21, do I get the problem correctly: 

If you use `plotSurface()` with parameters `pt_size = 2.75`, ` pt_alpha = 0.85` etc. you get the plot shown above. And you wanted to recreate the plot within the interface of plotSurfaceInteractive() with the same parameters and it looks like the one below? 

I can think of two reason why that might be the case: 

1. The parameter `pt_size` is given to parameter `size` of `ggplot2::geom_point()`. The smaller the window in which the plot is displayed the bigger the points appear. Apparently the window of plotSurfaceInteractive() is smaller than the one where you used plotSurface(). I'll try and rewrite the function to make sure that the size of the points does not depend any longer on the windows size. Till then you might have to "play around" with the size parameter in plotSurfaceInteractive() to make the plot like the one above. In your case you'd have to decrease the size of the points. 

2.  Within plotSurface() you have probably used parameter `smooth = TRUE`. With a `smooth_span = 0.25` I guess. This  makes the function use a loess fit (formula: variable ~ x + y) to smooth the color values locally. If you dont want this to happen set smooth = FALSE. Or set the default to FALSE via `obj <- adjustDefaultInstructions(obj, smooth = FALSE)`. If you want to use smoothing within `plotSurfaceInteractive()` just increase the smooth span via slider 'Spatial smoothing'. 

This has nothing to do with the denoising. 

Does that help?

**Comment by Rohitarora21** [comment]
Hi there! 

Thank you so much for the prompt response. I did not realize that the default instructions for the object were to use the loess fit.

Using obj <- adjustDefaultInstructions(obj, smooth = FALSE) has helped make the plots look a lot more similar.


I have one additional question, I am importing my data in using initiateSpataObject_ExprMtr, but the spatial coordinates are flipped in the y axis from what I'd expect them to be. For example, this is my current plot:

![image](https://user-images.githubusercontent.com/45678919/144677011-68ffeb18-c85b-44ef-b04a-8b25df4d65ed.png)

but this is what I would expect it to be like:

![image](https://user-images.githubusercontent.com/45678919/144677057-b4ed59be-eff0-4e77-b60e-518a94c53154.png)

I am currently using + scale_y_reverse() to flip the y axis, but can you think of any reasons this might be happening?

**Comment by kueckelj** [comment]
Do you have an histology image as background? Are coordinates and the image aligned? initiateSpataObject_ExprMtr()`  does not change the coordinates. So I don't know how the coordinates could be flipped. How does the plot look like if you plot the original coordinates data.frame (input for argument `coords_df` of `initiateSpataObject_ExprMtr()` if use 

`ggplot2::qplot(x = x, y = y, data = coords_df)`

**Comment by Rohitarora21** [comment]
![image](https://user-images.githubusercontent.com/45678919/144685487-4152a0cf-acf2-42f3-b88a-b0570e88d579.png)


yes I also have an image loaded in, but they are not aligned.

![image](https://user-images.githubusercontent.com/45678919/144686470-88260b96-6345-4183-9eeb-515f970d43e9.png)

**Comment by kueckelj** [comment]
I have added the function `flipImage()` to SPATA2s namespace. If you reinstall the master branch and then load, detach and load the package again you sould find it. Use it with your object like this: `obj <- flipImage(obj)`. It should account for the mismatched image and coordinates. I hope that suffices for now. I will look deeper in the "flipped image problem". However, I can not solve that right away as it probably requires me to change some baseline code and I dont want the package to become unstable.

If you have any questions left let me know! 

Best wishes 

Jan
