### ISSUE TITLE
Error while installing SPATA2

### ISSUE THREAD

**Issue by alicinwndlnd** [theMILOlab/SPATA2#138]
I kept getting an error message saying, "Error: object 'downloadRawData' is not exported by 'namespace::SPATAData'" whenever I tried to install SPATA2. Is this an issue with SPATAData or SPATA2? Is there anyway to fix it?

**Comment by ChenghaoJin-97** [comment]
I've met the same issue, MILO please help !!!

**Comment by zyfvae514** [comment]
Me too! How to solve this issue???

**Comment by kueckelj** [comment]
Hello everybody, sorry for that. Please install SPATAData again with install_github("theMILOlab/SPATAData"). Then install SPATA2 again with install_github("theMILOlab/SPATA2"). It should work again now.

Please note that we are on the verge of releasing SPATA2 v3.0.0 with the publication of the corresponding paper. SPATAData has undergone some changes lately in preparation for that - hence, the problem with the installation.
