### ISSUE TITLE
Trajectory Trends interpretation

### ISSUE THREAD

**Issue by MarcElosua** [theMILOlab/SPATA2#14]
Hello,
This is a great package and its super useful! Thanks so much for developing it.
I have a question regarding the interpretability of the AUC obtained from the `assessTrajectoryTrends`. As I understand AUC o would be the worst fit and 1 would be a perfect fit. Is it the opposite here?

Thanks so much,
Marc

**Comment by kueckelj** [comment]
Hello Marc, thanks four your kind feedback. AUC measures the area under the "residual curve".  If you have a look at Figure 4.1 in the [spatial trajectory tutorial](https://themilolab.github.io/SPATA2/articles/spata-v2-trajectory-analysis.html) you see the a dotted line in red in every "fitting plot". The green line represents the dynamic of a specific variable (here it is GFAP expression). Blue line represents the pattern the expression is fitted to. The lower the AUC of the red line - the residual line - the better the fit. Therefore AUC = 0 would be a perfect fit or the higher the AUC the worse the fit.

**Comment by MarcElosua** [comment]
This is great! Thanks so much!
