### ISSUE TITLE
Visium HD - Problem with creating SPATA object

### ISSUE THREAD

**Issue by vfincke** [theMILOlab/SPATA2#149]
Dear team, 

thank you for the nice package. 

I have data from the new Visium HD kit and am wondering if SPATA2 already wired with HD? 
I tried to make a SPATA2 object from my Stuart object, but get the follwing error: 

> validSpatialMethods()
[1] "Unknown" "Visium" 
> # create a spata-object from scratch
> spata_obj <- asSPATA2(object=eMRTskin_subset, 
+                      sample_name = "eMRTskin", 
+                      spatial_method = "Visium" )

12:30:24 Setting up new `spata2` object.
12:30:24 Transferring data.
Error in confuns::give_feedback(msg = msg, fdb.fn = fdb.fn, with.time = with.time,  : 
  Did not find value 'Spatial' of input for argument 'assay_name' among assays in Seurat object. Valid input options are: 'Spatial.008um' and 'sketch'.

Thank you in advance and kind regards, 
Victoria

**Comment by kueckelj** [comment]
Hello vfincke, with SPATA2 v3.0.0 which we released yesterday we offer support for VisiumHD. Under tab Tutorials of the new website you should find what you need to create it from scratch. The function is called `initiateSpataObjectVisiumHD()`. Alternatively, you can try it with `asSPATA2()` from a Seurat object.

Make sure to install the new version from the github master branch as suggested in tab Installation. 

Best 

Jan

**Comment by vfincke** [comment]
Thank you, it works now :)
