### ISSUE TITLE
'check_across_subset2' is not an exported object from 'namespace:confuns'

### ISSUE THREAD

**Issue by massonix** [theMILOlab/SPATA2#15]
Hi,

Thanks for developing this beautiful tool. Unfortunately, I'm getting this error when trying to install it:

```
Error : 'check_across_subset2' is not an exported object from 'namespace:confuns'
Error: unable to load R code in package ‘SPATA2’
Execution halted
ERROR: lazy loading failed for package ‘SPATA2’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/SPATA2’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/wd/1hh952ld20df7x0tpkb16c_r0000gn/T//RtmpVAkKG8/file92029756792/SPATA2_0.1.0.tar.gz’ had non-zero exit status
```

The problem seems to be in the [imported-function.R](https://github.com/theMILOlab/SPATA2/blob/master/R/imported-functions.R) script, line 55, where you import check_across_subset2 from the confuns package:

```
check_across_subset2 <- confuns::check_across_subset2
```

However, this function doesn't seem to exist in the confuns package.

Thanks for you help!

**Comment by kueckelj** [comment]
Hello, massonix. I've just merged the branches. If you install confuns again with `devtools::install_github("kueckelj/confuns")` the error should disappear. Could you try that and tell me if it works? 

(Make sure to restart the R session after reinstalling confuns.)

**Comment by massonix** [comment]
I could install it successfully, thank you!
