### ISSUE TITLE
Error in .subscript.2ary(x, , j, drop = TRUE) : subscript out of bounds

### ISSUE THREAD

**Issue by hlcxq1223** [theMILOlab/SPATA2#158]
Hello everyone,

I encountered some errors while running the code in the tutorial. Additionally, I noticed a discrepancy when reading the Pt4 folder using Seurat and SPATA2. The number of observations is 2943 in Seurat, but 2963 in SPATA2. Later, when I ran computeMetaFeatures, a warning message appeared: "Added features contain data for 2943 barcodes. SPATA object contains 2963. Missing barcodes get NAs as values." Does anyone know how to resolve this issue? Thanks

###########################################################################################
Pt4 <- removeSpatialOutliers(Pt4,
                              spatial_proc = TRUE,
                              rm_var = TRUE,
                              verbose = NULL)

23:41:35 Spatial outliers to remove: 28.
23:41:35 Keeping 2935 observation(s).
Error in .subscript.2ary(x, , j, drop = TRUE) : subscript out of bounds

###########################################################################################
> Pt4 <- computeMetaFeatures(Pt4,
                            assay_name = activeAssay(Pt4),
                            overwrite = TRUE)
Warning messages:
1: In addFeatures(object, feature_df = count_df, overwrite = TRUE) :
  Added features contain data for 2943 barcodes. Spata object contains 2963. Missing barcodes get NAs as values.
2: In addFeatures(object, feature_df = molecule_df, overwrite = TRUE) :
  Added features contain data for 2943 barcodes. Spata object contains 2963. Missing barcodes get NAs as values.

###########################################################################################
> plot_before <- 
   plotSurface(Pt4, color_by = "MAG") + labs(color = "MAG\n(Counts)")
Error in .subscript.2ary(x, i, j, drop = TRUE) : subscript out of bounds

###########################################################################################
> Pt4 <- normalizeCounts(Pt4, method = "LogNormalize")
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Warning: The following arguments are not used: layer
23:44:19 Active matrix in assay 'gene': 'LogNormalize'
Error in `map2()`:
ℹ In index: 3.
ℹ With name: sct_clip_range.
Caused by error in `ncol()`:
! object 'umi' not found
Run `rlang::last_trace()` to see where the error occurred.

**Comment by kueckelj** [comment]
Hello, I assume that Pt4 derives from data on you local device? Could provide some information about which platform you used? Visium, VisiumHD, MERFISH and how you initiated the object? You can go with show(object) which prints some valuable information I need for helping you. 

Furthermore, set `sct_clip_range = NULL` for now in `normalizeCounts()`.

**Comment by hlcxq1223** [comment]
> Hello, I assume that Pt4 derives from data on you local device? Could provide some information about which platform you used? Visium, VisiumHD, MERFISH and how you initiated the object? You can go with show(object) which prints some valuable information I need for helping you.
> 
> Furthermore, set `sct_clip_range = NULL` for now in `normalizeCounts()`.

Hi, kueckelj. Thanks for reply .I used the Visium data and initiated the object using  initiateSpataObjectVisium

> Pt4 <- initiateSpataObjectVisium(sample_name = "Pt4", 
                                  directory_visium = "/ST_matrix/Pt4/",
                                  mtr = "filtered",
                                  img_active = "hires",
                                  img_ref = "hires",
                                  verbose = TRUE)
00:08:07 Initiating SPATA2 object for platform Visium.
00:08:07 Reading count data from '/ST_matrix/Pt4/filtered_feature_bc_matrix.h5'.
00:08:11 Reading spatial and image data.
                                                                                                                  
00:08:11 Active image: 'hires'.
00:08:11 Computing pixel scale factor.
00:08:18 Active assay: 'gene'.
00:08:18 Active matrix in assay 'gene': 'counts'
00:08:18 Identifying tissue outline with `method = obs`.
> # show overview
> Pt4
SPATA2 object of size: 2963 x 38224 (spots x molecules)
Sample name: Pt4 
Platform: VisiumSmall 
Molecular assays (1):
Assay
 Molecular modality: gene
 Distinct molecules: 38224
 Matrices (1):
 -counts (active)
Images (1):
- hires (1820x2000 px, active)
Meta variables (2): sample, tissue_section

**Comment by kueckelj** [comment]
1. Is there any error trace or more information, you can give about the error message displayed: Error in .subscript.2ary(x, i, j, drop = TRUE) : subscript out of bounds. ?
2. Can you initiate the object again, skip the spatial outlier removal and see if the errors persists?

**Comment by hlcxq1223** [comment]
Hi, kueckelj. Thanks for your suggestion. The error was caused by the raw file 'tissue_positions_list.csv' having a different number of observations compared to the RDS file. After correcting this, I tried again, and it worked well. Thanks a lot.
