### ISSUE TITLE
loadExampleObject: Error in visium_spots$VisiumSmall[, c("barcode", "row", "col")] :

### ISSUE THREAD

**Issue by 964612858j5** [theMILOlab/SPATA2#163]
I am using SPATA version 3, and I encountered an error at the beginning of the "Creating Spatial Annotations" section in the tutorial when loading the data. The error message is as follows: 
```
> library(SPATA2)
> library(tidyverse)
> object_t313 <- loadExampleObject("UKF313T", process = TRUE, meta = TRUE)
Error in visium_spots$VisiumSmall[, c("barcode", "row", "col")] : 
  incorrect number of dimensions
```
After checking the data, it seems that `visium_spots$VisiumSmall` is composed of two lists, which may be causing the issue. Although I have temporarily fixed the issue by merging the two lists into a single dataframe, I am unsure if this will affect the subsequent analysis. Do you have any suggestions on how to resolve this? Thank you very much!

**Comment by kueckelj** [comment]
Hi, thanks for pointing that out. It does not affect the analysis. I changed `visium_spots` to a list of lists, and forgot to adjust `loadExampleObject()`. I'll fix it.

**Comment by 964612858j5** [comment]
Great! Thank you very much for your help!

**Comment by 964612858j5** [comment]
of course, let me try it now!
