### ISSUE TITLE
Spatial annotation visualization mismatch

### ISSUE THREAD

**Issue by 964612858j5** [theMILOlab/SPATA2#165]
Hi, Jan, I face a new problem. I am testing the "Spatial Annotation Screening" section with my own data and have created spatial annotations using createGroupAnnotations. However, when visualizing, I noticed that the outlines and regions do not align properly. Could you please suggest a solution for this issue? Thank you very much!
<img width="674" alt="3" src="https://github.com/user-attachments/assets/1cf5657d-0ad1-4fc7-8df4-a71bdafc9235">

**Comment by kueckelj** [comment]
Hi, can you show me the code with which you created the SpatialAnnotation? I assume you used `createGroupAnnotations()`?

**Comment by 964612858j5** [comment]
Thank you very much for your help! My data can be found at this link (https://drive.google.com/file/d/1OglgAba_MF_GY0U5ktdjefWnfx7V5wS7/view?usp=drive_link)
and my code is as follows:

library(SPATA2)
library(ggplot2)

# Load the data
dat=readRDS("object.rds")

# Generate the annotations
EMT_hotspot=rep("hotspot", nrow(dat@meta_obs))
EMT_hotspot[which(is.na(as.data.frame(dat@ meta_obs)[, "HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION_hot"]))]="no"

# Add the annotations into meta_obs
dat@ meta_obs=cbind(dat@ meta_obs, EMT_hotspot)

# Plot the left part
plotSurface(dat, color_by = "EMT_hotspot", pt_clrp = "jama") 

# Create annotations
getSpatAnnIds(dat)
dat <- createGroupAnnotations(
    object = dat, 
    grouping = "EMT_hotspot", 
    group = "hotspot",
    id = "EMT_hotspot", 
    force1 = TRUE
)
getSpatAnnIds(dat)

# Plot the right part: outline
cluster_ann_outline <- ggpLayerSpatAnnOutline(dat, ids = "EMT_hotspot")
plotImage(dat) + cluster_ann_outline

**Comment by kueckelj** [comment]
Can you try with `force1 = FALSE` and show me the output plots? If `TRUE`, one single annotation is created. In your case, you need multiple I think. The documentation of `createGroupAnnotations()` elaborates on this.

**Comment by 964612858j5** [comment]
You are right Jan! I indeed did not notice the parameter `force1`.  After setting `force1 = FALSE`, the result looks better, but they still do not include all the spots. <img width="660" alt="3" src="https://github.com/user-attachments/assets/f5cebf3c-f921-400d-9f38-b89201a86680">
After reading the help documentation, I also tried to modify the `grouping` and `group` with the following code, but the result still don't seem quite right. Even though I used multiple groups, `getSpatAnnIds(dat)` only returns one spatial annotations. 
```
library(SPATA2)
library(ggplot2)

dat=readRDS("object.rds")

EMT_hotspot=rep("hotspot", nrow(dat@meta_obs))
EMT_hotspot[which(is.na(as.data.frame(dat@ meta_obs)[, "HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION_hot"]))]="no"

dat@ meta_obs=cbind(dat@ meta_obs, EMT_hotspot)

plotSurface(dat, color_by = "EMT_hotspot", pt_clrp = "jama") 

getSpatAnnIds(dat)
dat <- 
  createGroupAnnotations(
    object = dat, 
    grouping = "HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION_hot_number", 
    group = names(table(dat@meta_obs[, 640])),
	#group = c("0_HCC-2T_HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION", "1_HCC-2T_HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION", "11_HCC-2T_HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION", "13_HCC-2T_HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION"),
    id = "hotspot", 
    force1 = FALSE,
	overwrite = TRUE,
	use_dbscan=FALSE
)
getSpatAnnIds(dat)#[1] "hotspot_1"

cluster_ann_outline <- ggpLayerSpatAnnOutline(dat, ids = getSpatAnnIds(dat))
plotImage(dat) + cluster_ann_outline
```
![4](https://github.com/user-attachments/assets/aa2c524c-3f57-4ee0-818a-6a2f301d3a38)

**Comment by kueckelj** [comment]
No, the last plot definetely is not right. If you want to include all of the small areas you need adjust `min_size`. These small islands of spots are probably discarded because as a spatial cluster identified by DBSCAN, they do not reach the limit of 1% of all observations. Given you sample, I assume that it features approx. 4600 spots. In order to be identified as a spatial annotation, each of these islands would need to have 46 spots - which they do not. Play around with the `min_size` parameter by reducing it. That should help.

**Comment by 964612858j5** [comment]
Amazing suggestion! I set min_size to 0, and the result is indeed much better! Thank you very much for your help!
![5](https://github.com/user-attachments/assets/0c25da0d-81d1-4f58-aabf-291e3fc4fe19)
