### ISSUE TITLE
use_scattermore documentation

### ISSUE THREAD

**Issue by simonmfr** [theMILOlab/SPATA2#167]
The documentation of plotSurface says "..If the number of data points plotted is bigger than 10.000 it is used anyway." however in plotSurface for data.frame it says
```
if(n_points >= 10000 & base::isTRUE(use_scattermore)){
````
Which option do we want to implement?

**Comment by kueckelj** [comment]
only if(`base::isTRUE(use_scattermore)). Actually, ggplot2 still works fast enough with up to 100.000. So we can increase the threshold to 100.000. If the object is created with more than 100.000 observations the object defaults to `use_scattermore = TRUE`. I adjust the initiate functions to give an informative message about this.
