### ISSUE TITLE
Error in plotSasLineplot()

### ISSUE THREAD

**Issue by A-Oncol** [theMILOlab/SPATA2#174]
Hello! I am trying to use the example data from the SPATA2 package. When I run:
 ``plotSasLineplot(object_t313, ids = necrotic_ids, variables = ‘HM_HYPOXIA’, line_colour = ‘blue’) + 
  labs(x = ‘Distance to Necrotic Borders [mm]’)`` 
the following error message appears:
``Error in `map()`:
ℹ In index: 1.
Caused by error in `map()`:
! unused argument (.f = function(r) {
    c(floor(r[1]), ceiling(r[2]))
})``
Then I run ``rlang::last_trace()`` and it showed:
```
<error/purrr_error_indexed>
Error in `map()`:
ℹ In index: 1.
Caused by error in `map()`:
! unused argument (.f = function(r) {
    c(floor(r[1]), ceiling(r[2]))
})
---
Backtrace:
     ▆
  1. ├─SPATA2::plotSasLineplot(...)
  2. │ └─SPATA2::getSasDf(...)
  3. │   └─SPATA2::compute_correction_factor_sas(...)
  4. │     └─purrr::map_df(...)
  5. │       └─purrr::map(.x, .f, ...)
  6. │         └─purrr:::map_("list", .x, .f, ..., .progress = .progress)
  7. │           ├─purrr:::with_indexed_errors(...)
  8. │           │ └─base::withCallingHandlers(...)
  9. │           ├─purrr:::call_with_cleanup(...)
 10. │           └─SPATA2 (local) .f(.x[[i]], ...)
 11. │             └─SPATA2::simulate_complete_coords_sa(...)
 12. │               └─getSpatAnnRange(object, id = id) %>% ...
 13. └─base::.handleSimpleError(...)
 14.   └─purrr (local) h(simpleError(msg, call))
 15.     └─cli::cli_abort(...)
 16.       └─rlang::abort(...)
```
Can you please help me how should I debug? Thank you very much!

**Comment by A-Oncol** [comment]
Hi, MILOlab! I re-installed the ``SPATA2`` package with ``devtools::install_github("theMILOlab/SPATA2", "dev")``, and re-run the ``plotSasLineplot(object_t313, ids = necrotic_ids, variables = ‘HM_HYPOXIA’, line_colour = ‘blue’) +  labs(x = ‘Distance to Necrotic Borders [mm]’)``. This time the error information is:
```
Error in !is.character(ids) || !ids %in% getSpatAnnIds(object) : 
  'length = 3' in coercion to 'logical(1)'
```
I would greatly appreciate your answers, thank you!

**Comment by kueckelj** [comment]
Hi, I'm looking into it right now.

**Comment by kueckelj** [comment]
Can you install the **development** branch again and see if it works now?

**Comment by A-Oncol** [comment]
> Can you install the **development** branch again and see if it works now?

OK, I'll try it right now. Thank you!

**Comment by A-Oncol** [comment]
> Can you install the **development** branch again and see if it works now?

Fantastic! It works! I am so appreciate for your wonderful tool and prompt reply!
