### ISSUE TITLE
transformSeuratToSpata() problem

### ISSUE THREAD

**Issue by yiranzhimo** [theMILOlab/SPATA2#19]
In SPATA2, I try to transform `seurat object` to `spata object` by the function transformSeuratToSpata()，but it has error：

>  Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'i' in selecting a method for function '[': Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102

**Comment by kueckelj** [comment]
Hello Yiranzhimo, 
if you use argument `verbose` = TRUE messages should appear that inform you about the progress of the function. Could you tell me which of the messages is the last message that appears before the function crashes?

**Comment by yiranzhimo** [comment]
> Hello yiranzhimo, if you use argument `verbose` = TRUE messages should appear that inform you about the progress of the function. Could you tell me which of the messages is the last message that appears before the function crashes?

run `tumour_spata <- transformSeuratToSpata(tumour_seurat,sample_name = "tumour_spata",assay_name="Spatial")`

the feedback of the transformSeuratToSpata function below:

>15:08:26 Setting up new spata-object.
15:08:26 Using SPATA's default gene set data.frame.
15:08:26 Checking input for validity.
15:08:26 Extracting spatial data from SpatialImage-object: 'slice1'
15:08:26 Extracting data matrices from assay: 'Spatial'
15:08:26 Extracting scaled expression matrix from slot: 'data'.
15:08:27 Transferring feature and dimensional reduction data.
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'i' in selecting a method for function '[': Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102

**Comment by kueckelj** [comment]
I have looked at it. It seems to have something to do with the sparse Matrices you Seurat object contains. 

Could you run the code below and see if some of the lines trigger the error:

`count_mtr <- tumor_seurat@assays[["Spatial"]]@counts

scaled_mtr <- tumor_seurat@assays[["Spatial"]]@scale.data

tryout_a <- count_mtr[base::rowSums(base::as.matrix(count_mtr)) != 0, ]

tryout_b <- scaled_mtr[base::rowSums(base::as.matrix(scaled_mtr)) != 0, ]`

**Comment by yiranzhimo** [comment]
> I have looked at it. It seems to have something to do with the sparse Matrices your Seurat object contains.
> 
> Could you run the code below and see if some of the lines trigger the error:
> 
> `count_mtr <- tumor_seurat@assays[["Spatial"]]@counts`
> 
> `scaled_mtr <- tumor_seurat@assays[["Spatial"]]@scale.data`
> 
> `tryout_a <- count_mtr[base::rowSums(base::as.matrix(count_mtr)) != 0, ]`
> 
> `tryout_b <- scaled_mtr[base::rowSums(base::as.matrix(scaled_mtr)) != 0, ]`

hello, when run `tryout_a <- count_mtr[base::rowSums(base::as.matrix(count_mtr)) != 0, ]`, it triggers the error:

> Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'i' in selecting a method for function '[': Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102

**Comment by kueckelj** [comment]
The problem your matrix has seems closely related to this problem: https://stackoverflow.com/questions/58302449/what-does-the-cholmod-error-problem-too-large-means-exactly-problem-when-conv . Could you try and modify the count matrix of your seurat object as proposed there and then try it again?

**Comment by yiranzhimo** [comment]
> The problem your matrix has seems closely related to this problem: https://stackoverflow.com/questions/58302449/what-does-the-cholmod-error-problem-too-large-means-exactly-problem-when-conv . Could you try and modify the count matrix of your seurat object as proposed there and then try it again?

Okay, I will try it, thank you for your help.
