### ISSUE TITLE
How to choose trajectory in Spatial trajectory analysis

### ISSUE THREAD

**Issue by yiranzhimo** [theMILOlab/SPATA2#20]
hello, I felt confused about trajectory drawing. I want to know how to choose the most appropriate trajectory to analysis.

**Comment by kueckelj** [comment]
There is no "most appropriate spatial trajectory" generally speaking. Spatial trajectory Analysis is an approach to connect two or more areas of interest und to screen for genes that transiently change along this connection in specific ways. E.g. you can use it to find genes whose expression increases the closer you get to a certain region or that peak in expression between two regions. What the "most appropriate trajectory" is depends on your biological question, the sample and the localization of the areas you are interested in.

**Comment by yiranzhimo** [comment]
> There is no "most appropriate spatial trajectory" generally speaking. Spatial Trajectory Analysis is an approach to connect two or more areas of interest und to screen for genes that transiently change along this connection in specific ways. E.g. you can use it to find genes whose expression increases the closer you get to a certain region or that peak in expression between two regions. What the "most appropriate trajectory" is depends on your biological question, the sample and the localization of the areas you are interested in.

yeah, you are right, thank you!

Thank for your work to create such a wonderful tool, I want to know more about it. I have another two questions about the method part of the paper.

Firstly, "**Two-dimensional representation of cellular states**" of the paper, what is the purpose of it, it functions in which analysis?

Secondly, "**Spatial distance measurement**" and "**Spatial overlap and correlation analysis**", I want to know why to address these steps in Spatial trajectory analysis?

**Comment by yiranzhimo** [comment]
> There is no "most appropriate spatial trajectory" generally speaking. Spatial Trajectory Analysis is an approach to connect two or more areas of interest und to screen for genes that transiently change along this connection in specific ways. E.g. you can use it to find genes whose expression increases the closer you get to a certain region or that peak in expression between two regions. What the "most appropriate trajectory" is depends on your biological question, the sample and the localization of the areas you are interested in.

yeah, you are right, thank you!

Thank for your work to create such a wonderful tool, I want to know more about it.                                                                        
I have another two questions about the method part of the paper.

Firstly, "Two-dimensional representation of cellular states" of the paper, what is the purpose of it, it functions in which analysis?

Secondly, "Spatial distance measurement" and "Spatial overlap and correlation analysis", I want to know why to address these steps in Spatial trajectory analysis?

**Comment by yiranzhimo** [comment]
> There is no "most appropriate spatial trajectory" generally speaking. Spatial Trajectory Analysis is an approach to connect two or more areas of interest und to screen for genes that transiently change along this connection in specific ways. E.g. you can use it to find genes whose expression increases the closer you get to a certain region or that peak in expression between two regions. What the "most appropriate trajectory" is depends on your biological question, the sample and the localization of the areas you are interested in.

yeah, you are right, thank you!

Thank for your work to create such a wonderful tool, I want to know more about it. 
I have another two questions about the method part of the paper.

Firstly, "Two-dimensional representation of cellular states" of the paper, what is the purpose of it, it functions in which analysis?

Secondly, "Spatial distance measurement" and "Spatial overlap and correlation analysis", I want to know why to address these steps in Spatial trajectory analysis?

Thank you!
