### ISSUE TITLE
Gradient analysis for a genes module or other covaritates

### ISSUE THREAD

**Issue by pedriniedoardo** [theMILOlab/SPATA2#206]
Hello, thank you very much for developing this tool.
I have a question about analyzing gradients in a dataset presented in the [vignette](https://themilolab.github.io/SPATA2/articles/spatial-trajectory-screening.html).
Is there a simple way to measure the gradient along the trend line for a set of genes (module) or any other covariate associated with the spots (like prop of mito reads or number of counts per spot) rather than a single gene expression?

**Comment by kueckelj** [comment]
Surce. You can use all sorts of numeric variables. The argument `variables` takes a character vector of variable names that must be "numeric". This example uses the variable `n_counts_gene` which contains (counts per spot). 

`object_t269 <- loadExampleObject("UKF269T", process = TRUE, meta = TRUE)`

`plotSpatialTrajectories(object_t269)`

`plotSurface(object_t269, "n_counts_gene") + `
`  ggpLayerSpatialTrajectories(object_t269, ids = "horizontal_mid") `
`plotStsLineplot(object_t269, variables = "n_counts_gene", id = "horizontal_mid")`

Is that what you mean?

**Comment by pedriniedoardo** [comment]
Thank you very much. This was precisely what I was looking for!
