### ISSUE TITLE
confusions about the method part

### ISSUE THREAD

**Issue by yiranzhimo** [theMILOlab/SPATA2#21]
Hello, I have another two questions about the method part of the paper.

Firstly, **"Two-dimensional representation of cellular states"** of the paper, what is the purpose of it, it functions in which analysis?

Secondly, **"Spatial distance measurement"** and **"Spatial overlap and correlation analysis"**, I want to know why to address these steps in Spatial trajectory analysis?

Thank you!

**Comment by heilandd** [comment]
Thanks a lot, these questions are related to the preprint not the SPATA package directly. Please email the authors directly to discuss certain questions. Thanks.
