### ISSUE TITLE
could not find function "plotDeaDotPlot"

### ISSUE THREAD

**Issue by DecodeGenome** [theMILOlab/SPATA2#22]
Hi,
I try to make a dotplot after de analysis, but SPATA2 could not find the function, could you please update your website instruction (https://themilolab.github.io/SPATA2/index.html). 
In addition, I did DE analysis with code below, I could not plot the heatmap, do I have to use "wilcox"?
AZ027SURG <-runDeAnalysis(object = AZ027SURG,
                          across = "seurat_clusters",
                          method_de = "bimod")
#################

Error in getDeaResultsDf(object = object, across = across, across_subset = across_subset,  : 
  No de-analysis results found across 'seurat_clusters' computed via method 'wilcox'.

Thanks,

Wei

**Comment by kueckelj** [comment]
Hello, the function `plotDeaDotPlot()` is exported in the namespace. Could you reinstall SPATA2 to make sure that you have the latest version? 

Regarding the method-problem. The default is 'wilcox'.  Therefore all functions refer to argument `method_de ` with 'wilcox'. Within the codechunk you posted above, you specified it within `runDeAnalysis()` but not within `getDeaResultsDf()`. Therefore the funcition told you, that no results for method 'wilcox' are available. If you want 'bimod' to be the default you can use the function `object <- adjustDefaultInstructions(object, method_de = 'bimod')`. 

Does that help?

**Comment by DecodeGenome** [comment]
Hello Dear SPATA2 developers:

Thank you very much for prompt response. That help our project move forward. Your accountable maintenance is the best one I have seen in the computational community.

Best wishes,

Wei
________________________________

**Comment by kueckelj** [comment]
Thank you for the kind feedback! Good look with your project.
