### ISSUE TITLE
Error when draw trajactory on spata-object

### ISSUE THREAD

**Issue by DecodeGenome** [theMILOlab/SPATA2#23]
Hi, after I ran "T2507 <-createTrajectories(object =T2507)", on the interactive window, when I chose "seurat-clusters" as features, the error occurs as "Error: Insufficient values in manual scale. 13 needed but only 10 provided."  this has happed on my two independent samples.  

Why this happens and how to solve this problem?

Thanks,

**Comment by heilandd** [comment]
This error occur if you chosen color palette has to less colors. You can just switch to ggplot2 default in the color palette to solve the problem.
