### ISSUE TITLE
plotTrajectoryHeatmap rearranges genes

### ISSUE THREAD

**Issue by MarcElosua** [theMILOlab/SPATA2#27]
Hi SPATA2 team,

Thanks again for the great package and functionalities! I'm trying to plot the heatmap of how some genes change over the trajectory but I would like to keep them in a specific order. When I set the parameter `arrange_rows = "none"` I understand the order should be unmodified. Instead the genes are ordered alphabetically. Is there something I'm missing here?
Any help will be really appreciated.

Thanks again for the package,
Marc

**Comment by kueckelj** [comment]
Hi Marc,
this is a good idea and in fact already an option. However, only in the development branch. 

You can install it with:

`devtools::install_github('theMILOlab/SPATA2', 'dev')`

Make sure to install the development branch of SPATAs helper package `confuns` with:

`devtools::install_github('kueckelj/confuns', 'dev')`

Once the packages are installed you can arrange the genes the way you want it with `arrange_rows = 'input' `. You might want to check out the argument `with_ggplot` as this makes the function use ggplot2 and `geom_tile()` to visualize the trajectory heatmap which I find handy given the options ggplot2 offers. If you prefer pheatmap you can leave it as is of course.

I haven't checked the development branch for bugs entirely. If anything doesn't work, please let me know! I'll do my best to fix it as quick as possible.

Best regards 

Jan

**Comment by MarcElosua** [comment]
Great! Thanks so much!
