### ISSUE TITLE
CNV analysis 

### ISSUE THREAD

**Issue by YuanningEric** [theMILOlab/SPATA2#28]
Hi,

When running the CNV analysis on tumor #T275 using the  `runCnvAnalysis` function, an error message occurred:

"13:24:54 Checking input for reference data.
13:24:54 Combining input and reference data.
13:24:55 Getting gene positions.
Error in base::is.data.frame(gene_pos_df) : 
  promise already under evaluation: recursive default argument reference or earlier problems?"

What may cause this problem?

**Comment by kueckelj** [comment]
Hello YuanningEric, 
sorry for the late reply. 

Can you try the following code chunk: 

` spata_object <- runCnvAnalysis(object = spata_object, gene_pos_df = SPATA2::gene_pos_df)`

Does that work?

**Comment by Dantferno** [comment]
Hi, thank you for the package :) 

I faced the same issue as YuanningEric and your code allowed the CNV analysis to proceed 

Good day to you

**Comment by simonmfr** [comment]
Hi @Dantferno, sorry for the long delay. In case this is still of interest, please retry with our updated SPATA2 v3 and the novel [CNV analysis tutorial](https://themilolab.github.io/SPATA2/articles/cnv.html).
