### ISSUE TITLE
raw count data

### ISSUE THREAD

**Issue by imkeller** [theMILOlab/SPATA2#29]
Hi! I was using SPATA2 to look at the data from this publication: https://www.nature.com/articles/s41467-022-28523-1. I loaded the SPATA2 object:

`s5 <- loadSpataObject("../raw_data/S5/S5_spata.objet.RDS")`

Now I wanted to take a look at the actual gene abundance data and I found 3 tables:

`s5@gdata$S5$counts$df`
`s5@gdata$S5$scaled$df`
`s5@gdata$S5$denoised$df`

Is the first one (counts) the raw count data? Thank you for your help!

**Comment by kueckelj** [comment]
Hi, that is correct. `counts` refers to the raw count data.
