### ISSUE TITLE
Cell counting per spot in spatial datasets and Cell counting per spot in spatial datasets

### ISSUE THREAD

**Issue by hzongyao** [theMILOlab/SPATA2#30]
Hi! I was using SPATA2 to look at the data from this publication: Spatially resolved multi-omics deciphers bidirectional tumor-host interdependencein glioblastoma，The method section of the article mentions details about the content related to Cell counting per spot in spatial datasets and Cell counting per spot in spatial datasets，I can't find the code in github, would you like to share the method detail to learn it? Thank you ！
 Thank you for your help!

**Comment by kueckelj** [comment]
Hello hzongyao, 
as this is a publication specific issue please contact dieter.henrik.heiland@uniklinik-freiburg.de for more information. 

Best regards 

Jan
