### ISSUE TITLE
Idea to extend trajectory analysis

### ISSUE THREAD

**Issue by simonmfr** [theMILOlab/SPATA2#31]
I would be interested in your thoughts on a possible new feature, similar to the trajectory analysis. Instead of measuring a trajectory from A to B, one could average the expression from multiple starting points towards a common target. As shown in the image the target could either be a point or an irregular structure, encircled by concentric rings.

![grafik](https://user-images.githubusercontent.com/70199914/165344389-0c937bf7-dce1-42fe-930b-b0437abe9b5f.png)

Any idea how to approach that task?

Best,
Simon

**Comment by kueckelj** [comment]
Hello simonmfr, thanks for the suggestion! We'll discuss it and I'll come back to you within the next few days!

**Comment by kueckelj** [comment]
Hi, we think this is a very interesting idea and we would love to help. Could you write me an email in which you give me an example of what you exactly hope to analyze and find? This is my adress: jan.kueckelhaus@uniklinik-freiburg.de .

Looking forward to it. 

Best regards 

Jan
