### ISSUE TITLE
Issue about the function SCTransform

### ISSUE THREAD

**Issue by yunbokai** [theMILOlab/SPATA2#32]
Hi,
SPATA2 is useful. But It seems that SCTransform is recommend by Seurat . I got
spata_obj@information$initiation$input$SCTransform
[1] FALSE
Why dont we use SCTransform? How to use it by default?
Thanks.

**Comment by kueckelj** [comment]
Hello yunbokai, 
you can use SCTransform during the initiation of the spata object with `initiateSpataObject_10X()` or with any other `initiateSpataObject_`-function. The initiate-functions are wrappers around the Seurat pipeline. You can read that in more detail in the description. For these functions to call SCTransform you need to set the argument `SCTransform` = TRUE. This would result in a call to SCTransform that uses its default. You can manipulate the arguments with which `SCTransform()` is used by setting the argument `SCTransform` = list(argument1 = input1, argument2 = input2, and so on). 

Please have a look at the details in the description of `initiateSpataObject_10X()`.

Does that work? And if so, does that help?

Best regards 

Jan

**Comment by yunbokai** [comment]
Hi Kueckelj

Thanks for your  kind anwsers！

Today, after studying SPATA2, I think  the question that "log-normalization fails to adequately normalize genes sometimes" will be dealed with the fuction "denoising". So SPATA2 does not set SCTransform=T as default. Am I right?

Best regards

yunbokai
