### ISSUE TITLE
Error in 'plotTrajectoryFeatures'

### ISSUE THREAD

**Issue by TehseusKunka** [theMILOlab/SPATA2#33]
Using 'plotTrajectoryFeatures' function, it comes the error 
'Error in hlpr_summarize_trajectory_df(object = object, ctdf = trajectory_object@compiled_trajectory_df,  : 
  object 'shifted_df' not found
But I cannot find the 'shifted_df' in the original code.
What can I do to analysis the trajectory features?
<img width="755" alt="image" src="https://user-images.githubusercontent.com/86277022/167352072-0b5df160-cee3-4ce3-b029-32ee76a10840.png">

**Comment by kueckelj** [comment]
Hello TehseusKunka, I can not reproduce the error. Can you reinstall SPATA2 and check if the error persists? It sounds familiar to me and I might have already fixed that. If the error persists after reinstalling (and reloading the package!): could you provide the complete function call with all the arguments?

**Comment by TehseusKunka** [comment]
> Hello TehseusKunka, I can not reproduce the error. Can you reinstall SPATA2 and check if the error persists? It sounds familiar to me and I might have already fixed that. If the error persists after reinstalling (and reloading the package!): could you provide the complete function call with all the arguments?

Thank you very much for the advice ! The problem has been solved after reinstalling the SPATA2.
