### ISSUE TITLE
SPATA2 Trajectory analysis with single-cell dataset

### ISSUE THREAD

**Issue by JihyunKiminGithub** [theMILOlab/SPATA2#35]
Dear SPATA2 developers,

I am currently working on single-cell dataset and want to draw plotTrajectoryHeatmap which cannot be supported by monocle3 (monocle 2 can do that). I know this tool is developed for Spatial Transcriptome dataset, but transformSeuratToSpata function fortunately accepts single_cell data. But when I use assessTrajectoryTrends or plotTrajectoryHeatmap, error pops up and I wonder how to solve these problems.

<img width="626" alt="image" src="https://user-images.githubusercontent.com/105287433/168471658-62739f41-5690-44c8-99e8-4c1771c3a6c3.png">
<img width="876" alt="image" src="https://user-images.githubusercontent.com/105287433/168471672-649bb339-248e-47dc-8c92-49f29534dd62.png">

Even though I changed the span parameter to 0, 0.0001, 0.1, 0.2, 0.3, error is still same.

# Codes #
Epi_SPATA <- transformSeuratToSpata(Epi1, method = "single_cell", sample_name ="Epi1",
                                           coords_from="umap",assay_name="RNA")
Epi_SPATA <- createTrajectories(object = Epi_SPATA)
plotTrajectoryHeatmap(object = Epi_SPATA,
                      trajectory_name = "Trajectory1",
                      variables = 'HM_HYPOXIA',
                      arrange_rows = "maxima",
                      show_row_names = FALSE,
                      split_columns = TRUE,
                      smooth_span = 0.3)
all_genes <- getGenes(Epi_SPATA)
all_gene_sets <- getGeneSets(Epi_SPATA)
atdf_gs <- assessTrajectoryTrends(object = Epi_SPATA,
                                  trajectory_name = "Trajectory1",
                                  variables = all_genes)
atdf_gene_sets <- assessTrajectoryTrends(object = Epi_SPATA,
                                         trajectory_name = "Trajectory1",
                                         variables = all_gene_sets)

Can I solve these errors when using single-cell dataset? Since I ran magic imputation and stored that information to the "data", I assume this could be one reason for the error.

Thanks,
Ji hyun

**Comment by simonmfr** [comment]
I had the same error, and I think it is because `assessTrajectoryTrends()` requires gene sets with >=2 genes. Try to delete all gene sets with only a single gene from the spata object, that worked for me:

```
library(tidyverse)
pathways <- spata_obj@used_genesets
temp <- pathways %>% group_by(ont) %>% summarise(n())
temp <- filter(temp,`n()`==1)
pathways <- pathways[!pathways$ont %in% temp$ont,]
spata_obj@used_genesets <- pathways
```

Otherwise you can check if the capitalisation of genes in the gene sets (`spata_obj@used_genesets$gene`) is compatible with the one in your data (`rownames(spata_obj@data$tbi_christina$scaled)`)

**Comment by JihyunKiminGithub** [comment]
When I re-do this work, this problem was solved suddenly. Thank you simon!
