### ISSUE TITLE
Mouse gene symbols

### ISSUE THREAD

**Issue by t-nejo** [theMILOlab/SPATA2#36]
Hello! 
I'm currently trying to analyze my 10X visium data of mouse brain using SPATA2. While my data sets had been mapped on the mouse reference in which the gene symbols begin with an uppercase letter followed by all lowercase letters, it seems to me that SPATA2 expects all uppercase feature names (gene symbols) for analyses, such as CNV and GSEA. 

As I also found that "Load10X_Spatial" function in Seurat had the option "to.upper = TRUE/FALSE", I attempted "to.upper = TRUE" within initiateSpataObject_10X(), but did not work, unfortunately. 

Although technically I can go back and manually edit the input data, it is complicated and labor-taking...
Does anyone have any thoughts on it? I appreciate your help!

**Comment by kueckelj** [comment]
Hey, I have changed the `initiateSpataObject_10X()` function. Can you set to.upper = TRUE when calling it and see if it fixes the problem?

**Comment by t-nejo** [comment]
Hi @kueckelj, 
After reinstalling the SPATA2, the gene symbols are shown in all upper cases and the gene set scores are calculated as expected. Thank you very much for your help!
