### ISSUE TITLE
Extract gene list showing specific trajectory pattern

### ISSUE THREAD

**Issue by JihyunKiminGithub** [theMILOlab/SPATA2#37]
Dear spata2 developers,

Hello, I am using spata2 packages and I think this package is so good to analysis single cell and spatial dataset. 

I am wondering Is there any way that we can extract genes that showing specific pattern across trajectories. (Please see the attached picture, I want to get four different gene sets.)

Thank you,
Jihyun Kim

<img width="869" alt="image" src="https://user-images.githubusercontent.com/105287433/170824234-0b70ed7a-85bb-4847-8c2c-023ed01bcf59.png">

**Comment by kueckelj** [comment]
Hello, did you create the attached plot with `plotTrajectoryHeatmap()`?

**Comment by JihyunKiminGithub** [comment]
> Hello, did you create the attached plot with `plotTrajectoryHeatmap()`?

Yes, I created above plot with plotTrajectoryHeatmap() and what I am wondering is whether I can get those gene list by matrix(?) so that I can easily access those arranged gene list. This function shows us the gene name, but for my analysis, there are so many genes so that they are overlapping and hard to identify.

Thanks,
Jihyun

**Comment by simonmfr** [comment]
Closed due to inactivity - please re-open if necessary.
