### ISSUE TITLE
Error when running plotTrajectoryHeatmap

### ISSUE THREAD

**Issue by kxxxjo** [theMILOlab/SPATA2#39]
Dear SPATA2 developer,

Hi all, thanks for developing useful tool.

When running `plotTrajectoryHeatmap`, the following error message occurred.

```
20:11:41 Joining 17192 genes.
20:11:45 Done.
20:11:49 Summarizing trajectory data.frame. (This might take a few moments.)
20:12:12 Done.
20:12:13 Smoothing values with smoothing span: 0.5.
Error in predLoess(object$y, object$x, newx = if (is.null(newdata)) object$x else if (is.data.frame(newdata)) as.matrix(model.frame(delete.response(terms(object)),  : 
na/nan/inf in foreign function call (arg 5)

```

so, I tried some ways to fix them but I couldn't fix.

In my data, there were no na/nan/inf. 

could you tell me the way to solve this error?

Thanks!

Best,
KJ

**Comment by kueckelj** [comment]
Hello KJ, I don't know why this error appears. For that, I'd need to have a look at your data. I have integrated a workaround in the function. Can you install SPATA2 again and check if the function still crashes? Instead of crashing it should now remove variables that can not be smoothed.
