### ISSUE TITLE
Cannot install the spata package

### ISSUE THREAD

**Issue by Rahakkk** [theMILOlab/SPATA2#41]
Hi, I have followed all the instructions in the installation tab on Spata 2.0 website. I have installed the package successfully previously on my other desktop. But I cannot install it now. I have installed all the required package previously then ran the code :
devtools::install_github(repo = "theMILOlab/SPATA2") 
and it is showing me as following : 

Downloading GitHub repo theMILOlab/SPATA2@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/theMILOlab/SPATA2/tarball/HEAD' failed

can you kindly tell me what's the fuss here?

**Comment by kueckelj** [comment]
Hello, Rahakk. 
I can not reproduce the error. I assume that the error message contained more details. Can you copy and paste me the complete error message as well as the messages that are printed out during the installation?

**Comment by Rahakkk** [comment]
<img width="642" alt="Screen Shot 2022-07-12 at 7 03 26 PM" src="https://user-images.githubusercontent.com/108989369/178496488-b4ca2b41-1dca-48cb-965e-26f62c18bba0.png">

**Comment by kueckelj** [comment]
I am sorry but I can still not reproduce the error. Does the some error occur if you try to install other packages from GitHub?

**Comment by heilandd** [comment]
Dear Rahakk,
this error can occur on the M1 systems. In case the download failed, you need to clone the repo and install SPATA2 from the local file system. The reason why M1 systems fail to download is not obvious. 

use: 

1. git clone https://github.com/theMILOlab/SPATA2.git

2. Then, you install by : devtools::install("to/your/path/SPATA2")

I hope this will answer your questions.
