### ISSUE TITLE
"Directory Does Not Exist"

### ISSUE THREAD

**Issue by abrana12** [theMILOlab/SPATA2#42]
Hi, I am trying to follow the instructions laid out for surface plotting: 
https://themilolab.github.io/SPATA2/articles/spata-v2-plotting-surface.html

While the libraries successfully load, I am unable to load objects. I'm new to this, so I'm probably doing something incorrectly but help would be appreciated! Thank you.

<img width="481" alt="image" src="https://user-images.githubusercontent.com/114631040/192931453-fb4aa092-a847-4531-a310-91f6ad2a6670.png">

**Comment by kueckelj** [comment]
Hello abrana12, 
the function loadSpataObject() reads from your device. I assume that you have not saved a spata2 object under the directory 'data/spata-obj-cortex256.RDS'. The tutorial is an old one and I will update them within the next weeks. Till then: As the paper has been published we provide the spata2 objects online using the package [SPATAData](https://github.com/theMILOlab/SPATAData). Install the package as described. Then, to run the tutorial you can use: `human_cortex <- downloadSpataObject(sample_name = "265_C", file = NULL)`. This will download the needed spata2 object. From there you should be able to use the tutorial interactively. 

Does that solve the problem? 

Best regards 

Jan

**Comment by abrana12** [comment]
Perfect, this resolved the problem. Thank you very much!
