### ISSUE TITLE
Error in CNV analysis

### ISSUE THREAD

**Issue by aaadc** [theMILOlab/SPATA2#46]
Hi, I use 'runCnvAnalysis' function to do the CNV analysis and got this error:

Error in addFeatures(object = object, feature_df = ordered_cnv_df2, overwrite = TRUE) : 
  Did not find any barcode-spots of the specified object in input for 'feature_df'.
Calls: runCnvAnalysis -> addFeatures -> <Anonymous>

I used 'initiateSpataObject_CountMtr' function to create the spata_obj with setting feature_df = NULL, is this cause the problem?

**Comment by kueckelj** [comment]
Hello aaadc, thanks for using SPATA2. I'll have a look at it and come back to!

**Comment by kueckelj** [comment]
Can you give me a screenshot or something similar of the output from `head(getFeatureDf(object = your_object)[["barcodes"]])`?

**Comment by aaadc** [comment]
> Can you give me a screenshot or something similar of the output from `head(getFeatureDf(object = your_object)[["barcodes"]])`?

Sure.
<img width="520" alt="image" src="https://user-images.githubusercontent.com/115471939/201564541-dbef7f9c-dd95-4d3b-8fdd-1c32de0f7351.png">

**Comment by kueckelj** [comment]
Whats the output of  `count_mtr <- getCountMtr(spata2); head(colnames(count_mtr))`?

**Comment by aaadc** [comment]
> Whats the output of `count_mtr <- getCountMtr(spata2); head(colnames(count_mtr))`?

I think you may refer to getCountMatrix() function? Because I got this error: 
<img width="695" alt="image" src="https://user-images.githubusercontent.com/115471939/201599988-935107ff-dfec-447f-97c6-787af090fa15.png">
And when I use getCountMatrix() function, I got this result:
<img width="676" alt="image" src="https://user-images.githubusercontent.com/115471939/201600111-5cf4f10d-4f03-4b1b-b077-4461b00271a5.png">

**Comment by kueckelj** [comment]
Im sorry, I meant `getCountMatrix()`. Thanks for correcting this. So no, `feature_df = NULL` is not the problem. I'll run this by my self with barcodes set to numbers. It might have something to do with this. I'll come back to you!

**Comment by kueckelj** [comment]
Alright, I think I have identified the problem. infercnv adds an X to numeric rownames. Therefore the output of infercnv can not be added to the spata object because it identifies your barcodes with X51550, X29579, etc. and then no barcodes match. I've just pushed the needed fix to the master branch that handles it. Can you install it again and see if it works for you now? 

In general, I suggest to prefix your barcodes with some letters (E.g. ID or BC) in case of numeric barcodes if you create your spata objects manually. Several functions might feature this weird behaviour with numeric barcodes.

**Comment by aaadc** [comment]
Thanks a lot for your help! I will add prefix to my barcodes and try again.

**Comment by kueckelj** [comment]
Sure, your welcome. Let me know if it worked out for you!

**Comment by aaadc** [comment]
It does work for me!  While I met another problem when plotting and I opened a new issue, could you please give me some suggestions?
