### ISSUE TITLE
Error in plotSurface()

### ISSUE THREAD

**Issue by aaadc** [theMILOlab/SPATA2#47]
I got an error when using plotSurface() function. 
<img width="797" alt="image" src="https://user-images.githubusercontent.com/115471939/202073510-8f5c1fb7-c52c-479a-a306-a12dedf225cf.png">
I was processing over 50 thousands spots. Does it really need that much memory？

**Comment by kueckelj** [comment]
Hello aaadc, I can't tell for sure but it might have to do something with the 50k spots. I have added an argument called `use_scattermore` to the function plotSurface(). If you set this to `TRUE` does the error disappear?

**Comment by jinyuanchun** [comment]
I have the same question, error message:
![image](https://github.com/theMILOlab/SPATA2/assets/40689145/3746aa21-ab85-4461-9d0b-754ef15c24e5)
Following the prompts, the problem has not been resolved yet

**Comment by simonmfr** [comment]
Hi @liangyuli12138, sorry for the late reply. Please re-try with SPATA2 v3 which has an updated faster architecture. If the error persists, feel free to re-open.
