### ISSUE TITLE
Error in runGsea

### ISSUE THREAD

**Issue by Shawn10312** [theMILOlab/SPATA2#48]
Hi, could you help me to debug this error?

> runGsea(object = spata_obj, 
                     across = "celltype",
                     gene_set_list = "BP.GO",
                     methods_de = "wilcox")

09:56:05 Working on group: 'Neoplastic cells 1' (8/8)
Step 1
Error in if (overlap < threshold) { : 
  missing value where TRUE/FALSE needed

Thanks a lot.

**Comment by kueckelj** [comment]
Hi Shawn10312, 
what exactly is the goal of `gene_set_list = 'BP.GO'? I assume that you only want to include gene sets of the BP.GO gene set list? 

Additionally, to help you I need the output of:

**Comment by Shawn10312** [comment]
Hi, re-run the codes, the same error.

>spata_obj <- runGsea(object = spata_obj, 
                     across = "celltype",
                     methods_de = "wilcox")

Working on group: 'Neoplastic cells 1' (8/8)
Step 1
Error in if (overlap < threshold) { :
missing value where TRUE/FALSE needed

>str(spata_obj@used_genesets)
tibble [936,495 × 2] (S3: tbl_df/tbl/data.frame)
 $ ont : chr [1:936495] "BC_RELA_PATHWAY" "BC_RELA_PATHWAY" "BC_RELA_PATHWAY" "BC_RELA_PATHWAY" ...
 $ gene: chr [1:936495] "IKBKG" "NFKBIA" "FADD" "CHUK" ...

>printGeneSetOverview(spata_obj)
  Class Available Gene Sets
1    BC                 289
2 BP.GO                7269
3 CC.GO                 972
4    HM                  50
5 MF.GO                1581
6  RCTM                1493



Thanks for your quick response!

**Comment by kueckelj** [comment]
Okay. I'm currently looking into this. Can you give me the outuput of: 

`printDeaOverview()`

and of 

`fdf <- getFeatureDf(object)` 
`levels(fdf[["celltype"]])`

**Comment by kueckelj** [comment]
I think I found the problem. This error occurs when a group does not have any upregulated genes. I fixed it such that the function gives you an informative message instead of crushing. Can you install the master branch again and try it?
