### ISSUE TITLE
suggestion of interactive visualization browser

### ISSUE THREAD

**Issue by Shiywa** [theMILOlab/SPATA2#5]
Hi, 
    thanks for your tools about spatial transcriptional profiles. recently, when I used `createSegmentation`, a interactive visualization browser appeared. I have some suggestion :
1. I just think the part displyed segment in the right of screen was too small to give user a great experence. 
2. for above question, part `instructions` could be designed more brief, and bar of parameter also could be more brief to leave more area to visualize. 
    thanks for your contribution again !

regards

**Comment by kueckelj** [comment]
Hello Shiywa, 
thanks for your suggestions. I'll try and incorporate them in the next version release. 

Best regards

Jan (SPATA-Team)
