### ISSUE TITLE
Adding new colour code

### ISSUE THREAD

**Issue by FPetitprez** [theMILOlab/SPATA2#52]
Hello,
Congrats on this great tool. I just wondered if there was a way to add other colour schemes to surface plots, besides what is listed in validColorPalettes() and validColorSpectra().
Thanks in advance.
Best wishes,
Florent

**Comment by kueckelj** [comment]
Hello FPetitprez, 
if you want to define color palettes once and then refer to them by name using arguments like `clrp` or `pt_clrp` I have to disappoint you. This is not possible. I'm sorry. Note, that you can always adjust color palettes using the `clrp_adjust` argument or add `ggplot2::scale_color_*()` to the output of plots to readjust the coloring as you desire.

**Comment by FPetitprez** [comment]
Hello, thanks for your response, that perfectly fits what I need! And congrats again for this fantastic tool!
Best wishes,
Florent
