### ISSUE TITLE
Converting SingleCellExperiment to SPATA2

### ISSUE THREAD

**Issue by YaobangWang** [theMILOlab/SPATA2#55]
Hi,
I am very pleased that SPATA2 has helped me so much in analyzing signal trajectory, and the plot produced by the function is pretty nice.
However, I was interested to know if there was a way to convert the object of a SingleCellExperiment into that of SPATA2. I would be very grateful if you had any code to solve this problem!

**Comment by kueckelj** [comment]
Hello YaobangWang,
Thanks for using SPATA2. I'll have a look into your request and will come back to you within the next few days. 

Best regards

Jan
