### ISSUE TITLE
 transform old seurat object to SPATA directly

### ISSUE THREAD

**Issue by hzongyao** [theMILOlab/SPATA2#6]
I want to keep old information from seurat object,so how to transform old seurat object to SPATA directly ? thank you !

**Comment by kueckelj** [comment]
Hello hzongyao,
have you tried `transformSeuratToSpata()`? If so, what data exactly was not transferred? Additionally, which Seurat Version are you using?

**Comment by hzongyao** [comment]
hi
Thanks for your amazing tools after I explore this library，I have read related methods about transform seurat obj to SPATA obj, There is indeed the phenomena of image plotting differently which results in mirror-inverted plots. I hope it can be solved in future!

Thank you!

**Comment by kueckelj** [comment]
Solving the issue with the mirror inverted plots is a point on my to-do list. I will let you know in this thread once I've uploaded the necessary function to align the coordinates. 

Did `transformSeuratToSpata()` solve the issue you've opened this threat for?

**Comment by TehseusKunka** [comment]
> 
> 
> Hello hzongyao,
> have you tried `transformSeuratToSpata()`? If so, what data exactly was not transferred? Additionally, which version of Seurat are you using?

Dear Professor
Now I have the same problem. I used Seurat to analyze the data and want to do a further analysis for trajectory. But i can not find the transformSeuratToSpata() command in the SPATA. Is the command deleted? 

Thank you!

**Comment by kueckelj** [comment]
Hello TehseusKunka, 
the command has not been deleted and should be in the namespace of SPATA2.  Are you using SPATA or SPATA2? Can you show me the error message that is displayed in your R console after using the command `SPATA2::transformSeuratToSpata()`?

**Comment by TehseusKunka** [comment]
> 
> 
> Hello TehseusKunka,
> the command has not been deleted and should be in the namespace of SPATA2. Are you using SPATA or SPATA2? Can you show me the error message that is displayed in your R console after using the command `SPATA2::transformSeuratToSpata()`?

Thank you. I was using SPATA, not SPATA2. I will try it later in SPATA2.
