### ISSUE TITLE
Cell type enrichment/deconvolution

### ISSUE THREAD

**Issue by rajeha** [theMILOlab/SPATA2#61]
Thank you for the useful toolset! Does the package implement a method for either signature-based or scRNA-based cell-type identification?

**Comment by heilandd** [comment]
Hi thanks for your comment. We have implemented RCTD and Spotlight,... and many more in SPATA3, which will be released soon. For know you can use the SPATAWrappers package which will be updated to novel tools as soon as they are avaiable. 

Here some helpful functions:
SPATAwrappers::runRCTD() or SPATAwrappers::inferSpotlight()

https://github.com/heilandd/SPATAwrappers

Best, Henrik

**Comment by rajeha** [comment]
That is very helpful, thank you Dr. Heiland! May I also suggest [cytoSPACE](https://www.nature.com/articles/s41587-023-01697-9
