### ISSUE TITLE
Different plots shown with plotSurface() and plotSurfaceInteractive()

### ISSUE THREAD

**Issue by RYY0722** [theMILOlab/SPATA2#62]
Hi there! Thanks a lot for the great tool!

Currently, I am plotting gene expressions with SPATA2. I found that the plot returned by `plotSurface` is quite different what is shown in `plotSurfaceInteractive()`. 
Plot returned by `plotSurface`
![image](https://user-images.githubusercontent.com/60810000/223005606-ee27784d-a96d-4bf2-9529-dedd50b44f18.png)
Plot returned by `plotSurfaceInteractive()`
![image](https://user-images.githubusercontent.com/60810000/223005752-6be15252-2560-41df-98eb-88005c63e59b.png)

How could these two plots be so different? Is there some smoothing or correction in the plotSurface function? Can we disable this? Since plotSurfaceInteractive requires manual adjustment, I really want to get the plot with plotSurface instead. Would you please give me some help regarding this? Thanks a lot!

**Comment by heilandd** [comment]
Yeah that's right. There is a default smoothing in the plotSurface. Just add smooth=F then it will be similar. This will be changed in the upcoming version of SPATA3. I can also recommend to use the autoencoder imputation instead on the smoothing (when it comes to low detected genes such ad PD-L1...) Best

**Comment by RYY0722** [comment]
Later I found that the smooth_span parameter seems to be (1-smooth) in the GUI. And it seems to work. And I mistakenly input PD-L1 instead of CD274.
