### ISSUE TITLE
Some question about your paper code

### ISSUE THREAD

**Issue by hulilalia** [theMILOlab/SPATA2#64]
Hello!

About theMILOlab/code_request/MALDI.R :

I run MALDI.R to regenerate processed maldi data, but there is some bug in line 187 `select(HMDH,names(as.data.frame(spectra_S1[r.ow, ,drop=F])))`.

In my opinion, there is no parameter nor variable named "r.ow". Is the 'r.ow' 'i' actually?

I want to repeat your image registration pipeline in your paper to get paired spatial matrix with mRNA counts and metabolites intensity. 

But we don't find the complete pipeline about aligning data from MALDI to stRNAseq. Would you like to give me some advice about where to find them?

Looking forward to your help!

Jiaxu Luo

**Comment by leotiwei** [comment]
> Hello!
> 
> About theMILOlab/code_request/MALDI.R :
> 
> I run MALDI.R to regenerate processed maldi data, but there is some bug in line 187 `select(HMDH,names(as.data.frame(spectra_S1[r.ow, ,drop=F])))`.
> 
> In my opinion, there is no parameter nor variable named "r.ow". Is the 'r.ow' 'i' actually?
> 
> I want to repeat your image registration pipeline in your paper to get paired spatial matrix with mRNA counts and metabolites intensity.
> 
> But we don't find the complete pipeline about aligning data from MALDI to stRNAseq. Would you like to give me some advice about where to find them?
> 
> Looking forward to your help!
> 
> Jiaxu Luo

Hello， have you resolved the related issues. I would appreciate it if you could contact me and discuss it together. My email [leoti@foxmail.com](mailto:leoti@foxmail.com).
