### ISSUE TITLE
Issue with Hyphenated Gene Symbols

### ISSUE THREAD

**Issue by vaidyagovind** [theMILOlab/SPATA2#67]
Hello,

I am trying to use the SurfacePlot function to visualize the distribution of our genes of interest, all of which contain dashes in the symbol. When I run the function, I get the following error: 

plotSurface(object = spata_obj, 
            color_by = 'MORC2-AS1', 
            smooth = FALSE, 
            pt_size = 1.8) 

08:53:21 Normalizing values.
08:53:21 Done.
Error in `geom_point_fixed()`:
! Problem while computing aesthetics.
ℹ Error occurred in the 1st layer.
Caused by error in `FUN()`:
! object 'MORC2' not found
Run `rlang::last_trace()` to see where the error occurred.

The above occurred when I tried to create a surface plot for MORC2-AS1. I tried using backticks as well, and received the following error:

Error in hlpr_join_with_aes(object = object, df = ., variables = c(alpha_by,  : 
  object 'MORC2-AS1' not found

Is there a way to visualize expression of genes that possess hyphenated gene symbols? I would greatly appreciate any guidance regarding a potential solution. 

Thank you very much for your help in advance.

**Comment by heilandd** [comment]
Normally this should not cause any problem. Lets see, can you show me the data.frame of the plot (p$data)

p= plotSurface(object = spata_obj,
color_by = 'MORC2-AS1',
smooth = FALSE,
pt_size = 1.8)

p$data

**Comment by vaidyagovind** [comment]
Good morning Dr. Heiland,

Thank you very much for your prompt reply. Below is the data.frame output from the code in your comment:

# A tibble: 3,878 × 5
   barcodes                               sample           x           y     `MORC2-AS1`
   <chr>                                    <chr>        <dbl> <dbl>       <dbl>
 1 AAACAACGAATAGTTC-1 #UKF242_T_ST  119.  45.4       0.844
 2 AAACAAGTATCTCCCA-1 #UKF242_T_ST  442. 379.        0.626
 3 AAACAATCTACTAGCA-1 #UKF242_T_ST  221.  66.3       0.673
 4 AAACACCAATAACTGC-1 #UKF242_T_ST  126. 435.        0.648
 5 AAACAGAGCGACTCCT-1 #UKF242_T_ST  414. 141.        0.575
 6 AAACAGGGTCTATATT-1 #UKF242_T_ST  104. 356.        0.556
 7 AAACATTTCCCGGATT-1 #UKF242_T_ST  422. 452.        0.645
 8 AAACCCGAACGAAATC-1 #UKF242_T_ST  492. 347.        0.531
 9 AAACCGGGTAGGTACC-1 #UKF242_T_ST  161. 323.        0.621
10 AAACCGTTCGTCCAGG-1 #UKF242_T_ST  214. 390.        0.552

**Comment by heilandd** [comment]
`plotdf <- joinWith(object, genes = "MORC2-AS1")
names(plotdf)[7] <- "gene"
plotSurface2(plotdf, color_by = "gene")`

**Comment by vaidyagovind** [comment]
Thank you, Dr. Heiland! This solution worked for me.
