### ISSUE TITLE
smooth algorithm in plotsurface

### ISSUE THREAD

**Issue by RYY0722** [theMILOlab/SPATA2#68]
Hi there, thanks a lot for the great work!!!

I am really impressed by the smoothing results of the plotsurface function and want to export the smoothed expression matrix. Would you please give me some help about how to do this? Or, would you suggest what kind of algorithm is used in this function? Thank you very much!

Best wishes,
Yuyan

**Comment by heilandd** [comment]
You can use the joinWith function which has the options to add smooth=T with the desired smooth_span,

Best
