### ISSUE TITLE
Seurat v5 compatibility: Error in `[.data.frame`(slot(object = x, name = "meta.features"), , i,  : unused argument (alist())

### ISSUE THREAD

**Issue by p-lombard** [theMILOlab/SPATA2#70]
Hi! I started having a problem with sub-setting spata objects and using the `transformSpataToSeurat()` function after installing the beta release of Seurat v5. I'll list some examples of the issue here: 

**1. Subsetting a spata object:**
```
spata_obj <-
  initiateSpataObject_10X(
    directory_10X = path,
    sample_name = name)
subs_barcodes <- df$barcodes # a char vector of barcodes we want to keep
spata_obj2 <- subsetByBarcodes_CountMtr(
                      spata_obj,
                      subs_barcodes)
```
Error message: 
> Starting initiation
> Calculating percentage of ribosomal and mitochondrial genes.
> Removing stress genes and mitochondrial genes.
> Error in '[.data.frame'(slot(object = x, name = "meta.features"), , i,  : 
>   unused argument (alist())

**2.  `transformSpataToSeurat()`:**
```
seurat_obj <- transformSpataToSeurat(object = spata_obj)
```
Error message: 
> Starting initiation
> Calculating percentage of ribosomal and mitochondrial genes.
> Removing stress genes and mitochondrial genes.
> Error in '[.data.frame'(slot(object = x, name = "meta.features"), , i,  : 
>   unused argument (alist())

It seems like the trace is coming from SPATA2 calling Seurat functions when initiating a new spata object. Perhaps the `meta.features` argument is being passed an invalid list? To trouble-shoot, I tried manually generating the `meta_data` variable in the  `transformSpataToSeurat()` source code. It seemed to have no issues, and its row names matched the column names of the counts matrix. 

I had no problems with my code last week and the only thing that I have changed since the last run is updating Seurat, so I'm pretty sure that's the source of the issue. I was just wondering if there might be any work-arounds or if you suggest just reverting to the CRAN version of Seurat? 
Thanks so much for your help and for creating such a great package! :) 

— Phoebe

**Comment by simonmfr** [comment]
Hi @p-lombard, sorry for the late reply. Please re-install SPATA2 and try using the following functions:

```
# load
spata_object <- SPATA2::initiateSpataObject_10X(directory_10X = path,
                                                sample_name = "abcd"
                                               )
# subset
spata_object <- SPATA2::subsetByBarcodes(spata_object, 
                                         SPATA2::getBarcodes(spata_object)[1:1000]
                                        )
# convert to Seurat
seurat_object <- SPATA2::asSeurat(spata_object,
                                  process = FALSE)
```

Otherwise, to transfer barcode metadata from SPATA2 to Seurat, an easy solution is:
```
meta_col <- as.data.frame(SPATA2::getFeatureDf(spata_object)[c("barcodes","column_to_transfer")])
seurat_object <- Seurat::AddMetaData(seurat_object, meta_col)
```

Hope that helps!
