### ISSUE TITLE
Error :  initiateSpataObject_10X()

### ISSUE THREAD

**Issue by tyaoi** [theMILOlab/SPATA2#71]
Hi!

I installed SPATA2 on R 4.3.0, and ran `initiateSpataObject_10X()` to create the spata object from CytoAssist-Visium FFPE data.
However, I got the following message and failed to create the object:

`invoke()` is deprecated as of rlang 0.4.0.
Please use `exec()` or `inject()` instead.

Now in my R, rlang 1.1.1 is installed. Moreover, this problem was not resolved simply by replacing to rlang old version.

Would you tell me any advice ?

Thanks,

Tyaoi

**Comment by kueckelj** [comment]
Hello Tyaoi, is it an error that crashes the function such that it does not return anything? Or is a warning message?

**Comment by tyaoi** [comment]
Hi kueckelj!

I made the common mistake of not putting the issue_positions.csv in the same directory as the other files. Problem is solved.

Thank you very much.

Tyaoi
