### ISSUE TITLE
Error in initiateSpataObject_10X

### ISSUE THREAD

**Issue by NorifusaIwahashi** [theMILOlab/SPATA2#73]
Thank you for creating such a wonderful analysis package.
I get the following error in the initiateSpataObject_10X function and no object is created. 
Please let me know how to resolve this error.

### My code
```
library(SPATA2)
library(Seurat)
library(tidyverse)
spata_obj <- initiateSpataObject_10X(
  directory_10X =  "path to my data directory",
  sample_name = "sample"
)
```
### Error message
> Error in setActiveMatrix() : 
>   argument "object" is missing, with no default
> In addition: Warning messages:
> 1: '~outs//' as sub directories are no longer required. See `?initiateSpataObject_10X`.
> This warning is displayed once per session. 
> 2: `invoke()` is deprecated as of rlang 0.4.0.
> Please use `exec()` or `inject()` instead.
> This warning is displayed once every 8 hours. 
> 3: In confuns::give_feedback(msg = msg, fdb.fn = fdb_fn, with.time = FALSE) :
>   Function `setActiveExpressionMatrix()` is deprecated and will be deleted by the end of 2022. Please use `setActiveMatrix()` instead.( used by .local() )

### Package info
 dplyr        * 1.1.2   2023-04-20 [1] CRAN (R 4.3.0)
 forcats      * 1.0.0   2023-01-29 [1] CRAN (R 4.3.0)
 ggplot2      * 3.4.2   2023-04-03 [1] CRAN (R 4.3.0)
 lubridate    * 1.9.2   2023-02-10 [1] CRAN (R 4.3.0)
 purrr        * 1.0.1   2023-01-10 [1] CRAN (R 4.3.0)
 readr        * 2.1.4   2023-02-10 [1] CRAN (R 4.3.0)
 Seurat       * 4.3.0   2023-04-28 [1] Github (weixiao1991/seurat@700faca)
 SeuratObject * 4.1.3   2022-11-07 [1] CRAN (R 4.3.0)
 SPATA2       * 2.0.0   2023-05-13 [1] Github (theMILOlab/SPATA2@b046167)
 stringr      * 1.5.0   2022-12-02 [1] CRAN (R 4.3.0)
 tibble       * 3.2.1   2023-03-20 [1] CRAN (R 4.3.0)
 tidyr        * 1.3.0   2023-01-24 [1] CRAN (R 4.3.0)
 tidyverse    * 2.0.0   2023-02-22 [1] CRAN (R 4.3.0)

### Platform info
 version  R version 4.3.0 (2023-04-21)
 os       macOS Ventura 13.3.1
 system   x86_64, darwin20
 ui       RStudio
 language (EN)
 collate  C
 ctype    en_US.UTF-8
 tz       Asia/Tokyo
 date     2023-05-14
 rstudio  2023.03.0+386 Cherry Blossom (desktop)
 pandoc   NA

**Comment by kueckelj** [comment]
Hello NorifusaIwahashi, 
this was a bug. I fixed it. Can you install it again and see if it works now? 

Best regards 

Jan

**Comment by NorifusaIwahashi** [comment]
Thanks for fixing the error. It worked fine.
