### ISSUE TITLE
Problem with creating SPATA2 object with my own count matrix and spatial coordinates !!

### ISSUE THREAD

**Issue by suvranath1** [theMILOlab/SPATA2#74]
Hello SPATA2 Developers,

I am trying to create my own "SPATA2" object with my own spatial spot count matrix of ~45,000 (unprocessed) and associated 3D coordinates (x, y and z). (also with 2D coordinates)

My count matrix (in .csv) looks like this:
![image](https://github.com/theMILOlab/SPATA2/assets/114509929/e3a884d4-1345-4043-82ce-1b2227bc8570)

and coordinate matrix (in .csv) looks like this:
![image](https://github.com/theMILOlab/SPATA2/assets/114509929/a89b2ed0-359e-4e6f-9d85-3b2fb9f747f7)

However, when I try to create the "SPATA2" object as per the tutorial mentioned here: 
https://themilolab.github.io/SPATA2/articles/spata-v2-object-initiation-and-manipulation.html

I am getting following error message in R:

![image](https://github.com/theMILOlab/SPATA2/assets/114509929/13c77db3-75a9-4edf-9b79-f2927f87f2b2)

Your suggestion/troubleshooting advice would be extremely helpful for me to proceed further with my spatial transcriptomics analysis with this wonderful pipeline!

Thank you in advance!

**Comment by kueckelj** [comment]
Hello suvranath1, thanks for using `SPATA2` can you give me the output of `is.numeric(count)` and of `count[1:5, 1:5]`.

Best regards 

Jan

**Comment by suvranath1** [comment]
Hello Jan,

Thanks for your reply. Here is the screenshot:

![image](https://github.com/theMILOlab/SPATA2/assets/114509929/f7b3c4d3-2f1f-4805-9e3f-65b9fb1ad2ff)

May be I will try with 2D coordinates considering only x and y coordinates, but I want to execute the pipeline with my own SPATA object. 

Looking forward to your reply.

Thanks,
Suvra

**Comment by suvranath1** [comment]
Hello Jan,

Thank for your reply. Here is the screeshot:

![image](https://github.com/theMILOlab/SPATA2/assets/114509929/58abc951-5a69-4c39-ad89-4ea782bf6c09)

Looking forward to your suggestion.

Thanks!

**Comment by kueckelj** [comment]
Can you install again and see if it works now?

**Comment by suvranath1** [comment]
Hi Jan,

No success so far. It is giving me following error now:

![image](https://github.com/theMILOlab/SPATA2/assets/114509929/2bd58552-1cf3-4e2b-ac72-313730595035)


Could you please provide me the info on how the "count matrix" and "coordinate data array" has been prepared and organized as a frame in your study (published work) ? So that I can also structure my input count and coordinates matrix accordingly?

Thanks,
Suvra

**Comment by kueckelj** [comment]
Hi! First, I think their is a type in your code example `is.matrix()` is probably what you wanted to write. The function should work regardless of specifics about the matrix. Are you sure that installation run successfully? I am asking because the updated version of the function can not return the error message you recieved as I have changed the code. Make sure to restart your RSession after installation. I have changed the code again. Can you install again, restart the session and then give me theoutput of: 

- currentSpata2Version()

Can you try again and see if it works now?

**Comment by ctwskychen** [comment]
hello kueckelj, I have successfully created SPATA object following your suggestion above. However, the getImage(spata_obj) returns the grayscaled image you can find attached. I read the image by using readPNG. the image itself is 16-bit colored image. I am wondering how to process with my image beforerunning getImage(object_t275).

looking forward to  your suggestion. thank you!
![question](https://github.com/theMILOlab/SPATA2/assets/124946138/eacd349d-b489-4175-ab2e-11f0734bbb2c)

**Comment by kueckelj** [comment]
Hello ctwskychen, do I get it right that the image you are reading is actually colorful but is displayed in grayscale if you create the `spata2` object the way you showed? If so, please install the package again and make sure to restart the R session! Then run the following code: 

`library(SPATA2)`

`image_obj <- createHistologyImaging(image = "my_dir_to_image", id = "322B")`

`# assuming that b is the coords_df and a is the count_mtr as you presented in your code example`
`spata_obj <- initiateSpataObject_CountMtr(coords_df = b, count_mtr = a, sample_name = "322B", image_object = image_obj)`

Does that work for you? 

Best regards 

Jan

**Comment by ctwskychen** [comment]
thanks kueckelj, it worked (getImage() funtion returns colorMode: color) for me after following your suggestion! However, plotSurface() function give out a grayed image as you can find below. I have uploaded the code and the corresponding result as well as the original PNG formatted iamge. Could you give me your suggestion? thank you.
best wishes, 

CTW
![Q](https://github.com/theMILOlab/SPATA2/assets/124946138/204a9fbf-ad7c-4db4-b3d3-4e0ee7b0e23a)

**Comment by kueckelj** [comment]
`plotSurface()` plots the observational units that underlie the image (e.g. barcode-spots in case of 10X Visium) in grey if `display_image = FALSE` and `color_by = NULL`, which is the default. Can you set `display_image = TRUE` and/or `color_by` to a variable of your choice and show me the output?

**Comment by kueckelj** [comment]
@suvranath1 As the error message says: The input for argument `coords_df` requires a data.frame that has at least the two variables _x_ and _y_. Both must be numeric. In your data.frame they seem to be of class character. `metadataa$x <- as.numeric(metadataa$x)` and `metadataa$y <- as.numeric(metadataa$y)` should do the trick. Does it work?

**Comment by kueckelj** [comment]
I'm closing this as complete. Reopen if necessary.
