### ISSUE TITLE
Copy Number Variations (CNV) gene_pos_df 

### ISSUE THREAD

**Issue by hzongyao** [theMILOlab/SPATA2#8]
hi
 I found the outcome related gene_pos_df of Running CNV-Analysis  is strange, Why some genes are located on chr 0，like ASAP3，Just like the website example, why do chr0, chr23, chr24 appear？
https://themilolab.github.io/SPATA2/articles/spata-v2-cnv-analysis.html

Thank you ！

**Comment by hzongyao** [comment]
I have read related code about how gene_pos_df is created, I hope the end outcome can exclude chr0,Thank you!

**Comment by kueckelj** [comment]
Hello hzongyao, 

the data.frame `gene_pos_df` is created by the function `CONICSmat::getGenePositions()`. [Code](https://github.com/theMILOlab/SPATA2/blob/master/R/cnv-analysis.R) Line 415. If you are not satisfied with the way this function outputs the gene position data.frame: 

I have updated the function `runCnvAnalysis()`. Using the argument `gene_pos_df` you can provide the data.frame the way you want it. This way you should be able to exclude chromosomes that you do not want to be part of the analysis. 

Does this solve the problem?
