### ISSUE TITLE
Problems with transformSeuratToSpata

### ISSUE THREAD

**Issue by llllkn** [theMILOlab/SPATA2#84]
I tried using the "transformSeuratToSpata" function to convert the spatial transcriptomics data from Seurat to Spata. The "images" variable I used contains information about the tissue slices. However, after applying the function, my "coordinates" remain as 0. Could you please advise on what might be causing this issue?
![微信截图_20230801165136](https://github.com/theMILOlab/SPATA2/assets/141127485/9005aa97-ca1d-41c4-a6fe-b2bd18b93ae3)
![微信图片_20230801165154](https://github.com/theMILOlab/SPATA2/assets/141127485/21d5bd53-8f0f-40f5-9481-2840eaa753ca)

**Comment by simonmfr** [comment]
Hi @llllkn, thank you for reaching out.

Can you please try ``asSPATA2()``? ``transformSeuratToSpata()`` has been deprecated in the meantime.

For a tutorial see: https://themilolab.github.io/SPATA2/articles/spata-v2-platform-compatibility.html

Best,
Simon
