### ISSUE TITLE
Converting giotto object to SPATA2

### ISSUE THREAD

**Issue by archana433** [theMILOlab/SPATA2#86]
Hi, When I am converting gitto object into spata2 object for cnv analysis , I am getting error :
spata2_obj <- 
  SPATA2::asSPATA2(
    object = giotto_object,
    sample_name = "visium", 
    spatial_method = "Visium", 
    transfer_meta_data = TRUE, 
    coordinates = spatial_locs,
    image_ebi = image_ebi,
    verbose = TRUE
  )

Error in as.data.frame.default(x[[i]], optional = TRUE) :
  cannot cast class 'structure("cellMetaObj", package = "Giotto")' to data.frame

![giotto_object](https://github.com/theMILOlab/SPATA2/assets/65083903/35abffc9-426d-4b21-9a53-1c59d5de243c)

Please help, how to resolve this error ?
Thank you

**Comment by simonmfr** [comment]
Hi, did you follow the pipeline described at https://themilolab.github.io/SPATA2/articles/spata-v2-platform-compatibility.html?

If you like you can send me a subset of your giotto file and I will have a try.

Best,
Simon

**Comment by simonmfr** [comment]
Closed due to inactivity, please feel free to re-open.
