### ISSUE TITLE
How to convert SPATA obj to AnnData obj ?

### ISSUE THREAD

**Issue by hzongyao** [theMILOlab/SPATA2#9]
Hi
stLearn is designed to comprehensively analyse Spatial Transcriptomics (ST) data to investigate complex biological processes within an undissociated tissue, I want to keep SPATA obj  information and then convert it to AnnData obj directly to apply the stLearn methods.

Thank you!

**Comment by heilandd** [comment]
There is no direct spata to annData function but you can to it through Seurat after spata to Seurat conversion. https://satijalab.org/seurat/archive/v2.4/conversion_vignette.html

Best regards, Spata team
