### ISSUE TITLE
Seurat v5 compatibility

### ISSUE THREAD

**Issue by ayushbharati** [theMILOlab/SPATA2#95]
This used to work completely fine but now it gives me an error out of nowhere.

13:25:34 Transferring data.
Error in value[[3L]](cond) : 
  Could not find count matrix in specified seurat object. Did you choose the correct method?
In addition: Warning message:
Layer ‘TRUE’ is empty

**Comment by AMAwatermelon** [comment]
seurat v5 problem

**Comment by acazelles** [comment]
I also have this problem. And I cannot create new SPATA2 object. 
Do you have a solution ?
Thanks for your help !
Antoine

**Comment by LvW-lab** [comment]
I had the same problem and was able to solve it by setting the assay_name to "SCT" (Instead of "Spatial") in the asSPATA2 function.
Hope this helps.
Lennart

**Comment by simonmfr** [comment]
Hi @ayushbharati, thanks for reaching out. Can you provide the function that you were running and your SPATA2 version?

**Comment by ayushbharati** [comment]
Hi @simonmfr This is my dummy code.
i <- 1
my_SP <- initiateSpataObject_10X(directory_10X = paste("/Users/ayushbharati/Dropbox/PAH_visium/2ndorder/Spaceranger/RL_A",i,"_S1/outs",sep = ""),
                        sample_name = paste("ph",i,sep = "")) 

and this is the error
                        
<img width="931" alt="image" src="https://github.com/theMILOlab/SPATA2/assets/63345976/db44a746-a397-4959-b64e-96c4466c3248">

**Comment by ayushbharati** [comment]
@simonmfr It is working now! Thank you very much!
