### ISSUE TITLE
Unable to load any objects on SPATA2

### ISSUE THREAD

**Issue by ssrinivasan2** [theMILOlab/SPATA2#99]
Hi,

I am new to this package and am trying to better visualize already processed Seurat Objects.

Similar to the other issues, I am unable to load any objects into SPATA2. I have tried uninstalling and re-installing SPATA2 and Seurat as well, but this did not change the issues. Could you please let me know if there is something I am doing wrong?

I am using R/4.3.2 and SPATA2 v2.0.4 and Seurat v5.0.1.

I have tried several commands from the GitHub tutorial:

1. Loading Seurat objects

seurat_object <- SeuratData::[LoadData](https://satijalab.org/seurat/reference/LoadData.html)("stxBrain", type = "anterior1")
seurat_object <- Seurat::[SCTransform](https://satijalab.org/seurat/reference/SCTransform.html)(seurat_object, assay = "Spatial", verbose = FALSE) 

spata2_object <- 
  SPATA2::[asSPATA2](https://themilolab.github.io/SPATA2/reference/asSPATA2.html)(
    object = seurat_object,
    sample_name = "mouse_brain",
    image_name = "anterior1", 
    spatial_method = "Visium"
    )

2. Loading 10x data directly

object_t275 <-
  [initiateSpataObject_10X](https://themilolab.github.io/SPATA2/reference/initiateSpataObject_10X.html)(
    directory_10X = "path/to/a/10Xvisium-folder", # the directory from which to load the data
    sample_name = "gbm-275"
    )

3. Loading SPATA objects from SPATAdata

object_t269 <- downloadSpataObject(sample_name = "269_T")

In all three cases, I get this error: 

Error in give_feedback(msg = msg, verbose = verbose, fdb.fn = fdb.fn,  :

**Comment by kueckelj** [comment]
Hello, thanks for reaching out to us. Can you install confuns again and see if the error persists?

**Comment by kueckelj** [comment]
I am looking into it. I will come back to you in no time.

**Comment by kueckelj** [comment]
Can you install confuns again and try again?

**Comment by healthgreat** [comment]
**I reinstalled Confuns, but if I load it from scratch using initiate SpataObject=10X, it still prompts Error in getActiveMatrixName (object, verbose=FALSE):
Please set an active matrix with ` setActivenMatrix()`
I suspect that this setActivenMatrix is spelled incorrectly. Shouldn't it be setActiveMatrix?**

> devtools::install_github(repo = "kueckelj/confuns",force = TRUE)
Downloading GitHub repo kueckelj/confuns@HEAD
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\Administrator\AppData\Local\Temp\RtmpCmCvtN\remotes1a1c77f7701e\kueckelj-confuns-3f03060/DESCRIPTION' ...
─  preparing 'confuns': (497ms)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts (398ms)
─  checking for empty or unneeded directories
─  building 'confuns_1.0.3.tar.gz'
   
* installing *source* package 'confuns' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Note: possible error in 'validColorSpectra(flatten = TRUE)': unused argument (flatten = TRUE) 
Note: possible error in 'validColorPalettes(flatten = TRUE)': unused argument (flatten = TRUE) 
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (confuns)

**> object_t275 <-initiateSpataObject_10X(**
+     directory_10X = "./rawdata/CR_22_17626_FP_R_SSV_1/", # the directory from which to load the data
+     sample_name = "CR_22_17626_FP_R_SSV_1"
+     )
11:01:57 Starting initiation.
11:01:57 No gene-set data.frame path specified.
11:01:57 Reading in .h5 file.
11:01:57 Loading from directory: './rawdata/CR_22_17626_FP_R_SSV_1/'
11:01:59 Performing Seurat-analysis steps.
11:01:59 Calculating percentage of ribosomal and mitochondrial genes.
11:01:59 Removing stress genes and mitochondrial genes.
11:01:60 Skip running 'SCTransform()' as it's argument input is neither TRUE nor a list.
11:01:60 Running 'Seurat::NormalizeData()' with specified parameters.
Normalizing layer: counts
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
11:02:01 Running 'Seurat::FindVariableFeatures()' with specified parameters.
Finding variable features for layer counts
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
11:02:03 Running 'Seurat::ScaleData()' with default parameters.
Centering and scaling data matrix
  |================================================================================================| 100%
11:02:05 Running 'Seurat::RunPCA()' with specified parameters.
PC_ 1 
Positive:  APOE, CD74, LAPTM5, C11orf96, TYROBP, C3, HLA-DRA, CTSD, C1QB, C1QC 
	   FABP4, IFI30, SRGN, HLA-DPB1, PECAM1, SLC11A1, OLR1, GPX3, CCN1, G0S2 
	   THBS4, APOD, COL6A3, TYMP, PLIN2, CD68, C1QA, ZNF331, ANGPTL4, ADAMTS1 
Negative:  SPINT2, TFF1, C19orf33, LGALS4, ATP1B1, FXYD3, ELF3, S100A6, MUC1, CTSE 
	   TFF2, CBLC, TMC5, GPRC5A, CYP3A5, GOLM1, RHPN2, KRT8, ID1, SPINK1 
	   S100P, TNS4, VASP, INAVA, KRT18, LSR, ACTN4, ABCC3, MUC5AC, TMPRSS4 
PC_ 2 
Positive:  CTSB, MMP14, FBP1, CTSD, IL32, TIMP3, TGFBI, TREM1, SLC11A1, KRT7 
	   CAPG, SPP1, LAMB3, COL6A3, DDIT4, IFI27, UBD, KRT8, IFI6, MARCO 
	   CLTB, LAPTM5, TAGLN2, OLR1, MMP11, S100A4, CXCL5, S100A10, MMP12, CD68 
Negative:  IGFBP3, CLU, CXCL14, IGFBP5, PRELP, APOD, C7, GCG, PTGDS, DMBT1 
	   SOD3, DPEP1, IGHA1, HEYL, MSMB, OLFM4, MGP, SYNPO2, HSPB6, COL14A1 
	   SLC40A1, JCHAIN, PPP1R1B, ADIRF, IGHM, TFF2, BPIFB1, ELN, EPHA3, IGHG4 
PC_ 3 
Positive:  APOE, UBD, FABP4, IFI6, TYROBP, LAPTM5, IFI30, HMGA1, LYZ, C1QC 
	   C1QB, CTSD, APOC1, TYMP, CCL18, IFI27, CD74, CD36, SLC11A1, ST14 
	   OLR1, AQP9, AQP1, FBP1, PSMD8, SPINK1, GPX3, JPT1, VIL1, C1QA 
Negative:  COL10A1, TAGLN, COL5A1, THBS2, CALD1, STMN2, INHBA, COL5A2, ANTXR1, COL12A1 
	   COL11A1, IGFBP3, IGFBP5, LOXL2, TIMP3, NPR3, HOPX, SLC44A1, PALLD, DPYSL3 
	   CXCL14, HTRA1, POSTN, MMP2, ITGA11, SULF1, MIF, LTBP1, CST1, NR4A1 
PC_ 4 
Positive:  KRT7, CLTB, EPHB6, MALL, UBD, DHRS9, TM4SF1, COL17A1, PMEPA1, SOD3 
	   KRT23, TACSTD2, DES, CDH1, TNFRSF21, MELTF, KLK6, ITGB6, SERPINB2, ITGA3 
	   CDA, VWF, IGLC1, C7, ITGB4, KRT16, ADIRF, ITGA2, LAMB3, THBS4 
Negative:  LYZ, DMBT1, BPIFB1, SPP1, MSMB, CTSB, CTSD, SLC11A1, MUC5B, CD68 
	   HIST1H1B, FBP1, FCER1G, OLR1, LSP1, LAPTM5, OLFM4, APOC1, MARCO, FCGR3A 
	   INHBA, COL11A1, AQP5, PPP1R1B, IFI30, SLC17A9, TRNP1, ANPEP, S100A9, ITGAX 
PC_ 5 
Positive:  FOSB, NR4A1, MIDN, MUC5AC, IER3, CCN1, DES, GREM1, LOXL2, ID1 
	   IER2, PSCA, AQP5, LFNG, REG4, MMP2, TRNP1, ACTG2, MARCKSL1, ACTN4 
	   C11orf96, MCAM, SULT1C2, EGR3, PXDN, BCL3, COL12A1, COL11A1, GPX3, COL6A3 
Negative:  GCG, IGKC, IGHA1, CXCL14, CST1, IGFBP3, JCHAIN, STRA6, IGFBP5, DPEP1 
	   IGHM, IGHG4, SERPINA1, IGHJ6, IGHG1, EPHA3, SST, IGKV4-1, TTR, PRELP 
	   MMP7, INS, FABP1, COLEC11, MOGAT1, CHGB, FBP1, ADAMTSL2, CHGA, APOD 
11:02:14 Running 'Seurat::FindNeighbors()' with specified parameters.
Computing nearest neighbor graph
Computing SNN
11:02:15 Running 'Seurat::FindClusters()' with specified parameters.
Modularity Optimizer version 1.3.0 by Ludo Waltman and Nees Jan van Eck

Number of nodes: 3947
Number of edges: 152994

Running Louvain algorithm...
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Maximum modularity in 10 random starts: 0.7921
Number of communities: 13
Elapsed time: 0 seconds
11:02:15 Running 'Seurat::RunTSNE()' with default parameters.
11:02:22 Running 'Seurat::RunUMAP()' with specified parameters.
11:02:22 UMAP embedding parameters a = 0.9922 b = 1.112
Found more than one class "dist" in cache; using the first, from namespace 'BiocGenerics'
Also defined by ‘spam’
11:02:22 Read 3947 rows and found 30 numeric columns
11:02:22 Using Annoy for neighbor search, n_neighbors = 30
Found more than one class "dist" in cache; using the first, from namespace 'BiocGenerics'
Also defined by ‘spam’
11:02:22 Building Annoy index with metric = cosine, n_trees = 50
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
11:02:22 Writing NN index file to temp file C:\Users\ADMINI~1\AppData\Local\Temp\RtmpCmCvtN\file1a1c4d336de
11:02:22 Searching Annoy index using 1 thread, search_k = 3000
11:02:22 Annoy recall = 100%
11:02:23 Commencing smooth kNN distance calibration using 1 thread with target n_neighbors = 30
11:02:24 Initializing from normalized Laplacian + noise (using RSpectra)
11:02:24 Commencing optimization for 500 epochs, with 168256 positive edges
Using method 'umap'
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
11:02:33 Optimization finished
11:02:33 Initiating `spata2` object.
11:02:33 Setting up new `spata2` object.
11:02:33 Transferring data.
11:02:35 Done.
11:02:35 Saving.
11:02:35 No directory specified. Skip saving `Seurat` object.
11:02:35 Computing pixel scale factor.
11:02:35 Using center to center distance to compute pixel scale factor.
11:02:35 Computing barcode spot distances.
11:02:38 Done.
Error in getActiveMatrixName(object, verbose = FALSE) : 
  Please set an active matrix with `setActivenMatrix()`
In addition: Warning message:
Not validating Seurat objects

**Comment by YingXu-FDU** [comment]
Hi there, i met with the same problem.
Error in getActiveMatrixName(object, verbose = FALSE) : 
  Please set an active matrix with `setActivenMatrix()`

have you fixed it?

**Comment by simonmfr** [comment]
Thank you for raising this issue. Please update SPATA2 and confuns, and try again. It should work now.

**Comment by simonmfr** [comment]
Closed due to inactivity - please re-open if the issue persists.
